### ISSUE TITLE
Update notificationText and notificationTile  text

### ISSUE THREAD

**Issue by yusmi25** [Dev-hwang/flutter_foreground_task#1]
hello, great package.
Can I update the notification text, because I'm using counting timer on the notificationText
thanks.

**Comment by Dev-hwang** [comment]
> hello, great package.
> Can I update the notification text, because I'm using counting timer on the notificationText
> thanks.

Try updating to  `flutter_foreground_task: ^1.0.8`.

And using the `update` function, you can update the notification title and content.
Whenever the notification is updated, a sound or vibration may occur.
Therefore, it is recommended to set `channelImportance` and `priority` to LOW or less.

```dart
  final flutterForegroundTask = FlutterForegroundTask.instance.init(
    notificationOptions: NotificationOptions(
      channelId: 'notification_channel_id',
      channelName: 'Foreground Notification',
      channelDescription: 'This notification appears when a foreground task is running.',
      channelImportance: NotificationChannelImportance.LOW,
      priority: NotificationPriority.LOW
    ),
    foregroundTaskOptions: ForegroundTaskOptions(
      interval: 5000
    )
  );

  int count = 0;
  void startForegroundTask() {
    flutterForegroundTask.start(
      notificationTitle: 'Foreground task is running',
      notificationText: 'Tap to return to the app',
      taskCallback: (DateTime timestamp) {
        print('timestamp: $timestamp');

        count++;
        flutterForegroundTask.update(
          notificationTitle: 'count: $count',
          notificationText: 'count: $count'
        );
      }
    );
  }
```

The `update` function does not have to be implemented inside `taskCallback`. However, please use it after calling the `start` function.

**Comment by am2074** [comment]
This solution provided does not work anymore for anyone trying to do what the original user wanted to solve. I'm using the latest version of this and this solution does not activate`FlutterForegroundTask.update`. Is there anyway to fix this?

**Comment by Dev-hwang** [comment]
@am2074 

Many things have changed since version 2.0.0. check readme.
