### ISSUE TITLE
About the start function

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#10]
When we call 
``await FlutterForegroundTask.start(
    notificationTitle: "Today: $steps steps",
    notificationText: 'Yesterday: $yesterdaySteps steps',
    callback: periodicTaskFun,
  );
``
Does this call creates a new isolate or is the service still running in the main isolate?

**Comment by Dev-hwang** [comment]
@darshansatra1 

When the `FlutterForegroundTask.start` function is called, a new isolate is created separate from the main isolate. The isolate of dart  has a separate memory area unlike the threads used in other languages. Therefore, `periodicTaskFun` is executed in the new isolate and the event is called periodically by creating a background method channel through `FlutterForegroundTask.initDispatcher` function.

If you want to share data with an isolate that has separate memory areas, try the [sqflite](https://pub.dev/packages/sqflite) plugin.

As I am still learning, it may not be a perfect answer, but I hope it helps you :)

**Comment by darshansatra1** [comment]
Yaa I faced the issue in Hive, since Hive doesn't support multi-threading. So I switched to object box which had better performance than sqflite and also supports multi-threading.
