### ISSUE TITLE
App not finding start callback in release build. Flutter version 3.3.0

### ISSUE THREAD

**Issue by GidRamch** [Dev-hwang/flutter_foreground_task#100]
I've already resolved the issue. I'm just posting here incase it can be helpful to other devs in the future.

Also, if you think it can be solved in a better way, please let me know, thanks!

TL;DR: Add the pragma decorator to the top level start callback function as follows.

```dart
@pragma('vm:entry-point')
void foregroundServiceStartCallback() {
  FlutterForegroundTask.setTaskHandler(TimerTaskHandler());
}
```

This will ensure that the code is included in the final build.

**Comment by ksheremet** [comment]
Just hit the same issue now.  Thanks for the workaround, it works!

Posting my error log here to make the issue more discoverable:

```
E/flutter (31674): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:.....dart' not found.
E/flutter (31674): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (31674): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter (31674): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (31674): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
```

Worth noting that `FlutterForegroundTask.startService` still returns `true` in this case.

**Comment by GaelleJoubert** [comment]
I had the exact same issue in release.
 I try to add the `@pragma('vm:entry-point')` , but now my app is actually crashing instead of displaying the `Dart Error: Dart_LookupLibrary ...`.
 It is working fine in debug.
