### ISSUE TITLE
Pass parameters to the callback function

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#11]
```
Future<void> startPeriodicTask({
  required int steps,
  required int yesterdaySteps,
}) async {
  await FlutterForegroundTask.start(
      notificationTitle: "Notification", 
      callback: periodicTaskFun,
);
}
```
Right now I'm using this code to register the callback function, but can I pass parameters like String or Int to periodicTaskFun? If not please can you add such a feature?

**Comment by Dev-hwang** [comment]
Since the periodicTaskFun function is a top-level function, parameters cannot be passed directly. Use a mobile database like sqlite.

This is an example using sqflite. https://github.com/Dev-hwang/flutter_foreground_task/issues/9#issuecomment-887955423

**Comment by darshansatra1** [comment]
Can you please go through this [Object Box Issue](https://github.com/objectbox/objectbox-dart/issues/288#issue-954780617). I have been trying to get the same instance of Store but as I'm making an instance from 2 different isolates the HashCodes are not the same because of which I'm not able to access the same store.

**Comment by Dev-hwang** [comment]
I've checked the requirements, but there doesn't seem to be a way right now. I'll keep thinking about how to pass a SendPort or parameters.

**Comment by darshansatra1** [comment]
Yes, it would be of great help if we can send some parameters in the **callback** function or can communicate with the main isolate.

**Comment by darshansatra1** [comment]
```
```

**Comment by darshansatra1** [comment]
```

Future<void> startPeriodicTask({
  required int steps,
  required int yesterdaySteps,
  required Store store,
}) async {
  var port = ReceivePort();
  IsolateNameServer.registerPortWithName(port.sendPort, mainIsolatePortName);
  await FlutterForegroundTask.start(
    notificationTitle: "Today: $steps steps",
    notificationText: 'Yesterday: $yesterdaySteps steps',
    callback: periodicTaskFun,
  );
  final taskPort = (await port.first) as SendPort;
  taskPort.send(store.reference);
  IsolateNameServer.removePortNameMapping(mainIsolatePortName);
}


void periodicTaskFun() async {
  Stream<StepCount> _stepCountStream = Pedometer.stepCountStream;
  StreamSubscription<StepCount>? streamSubscription;
  final port = ReceivePort();
  IsolateNameServer.lookupPortByName(mainIsolatePortName)!.send(port.sendPort);
  final storeRef = (await port.first) as ByteData;
  LocalDataSource localDataSource = LocalDataSourceImpl();
  await localDataSource.initializeForForegroundService(reference: storeRef);
  FlutterForegroundTask.initDispatcher((timeStamp) async {
    if (streamSubscription != null) {
      return;
    }...
```
So this was the solution I got from Internet and it's working now. But when I kill the app and reopen it,  It's throwing me an error.

Error:
```
 Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: step_count. Response ID: 0
```

Do you have any idea why this is happening?

**Comment by Dev-hwang** [comment]
The above problem occurs if the `cancel` function of `streamSubscription` is not called. If the problem persists despite writing the code, check if the onDestroy in the initDispatcher function is working properly.

**Comment by darshansatra1** [comment]
So I checked the onDestroy function and it is working. But this error actually occurs when in the following steps:
1. I run the foreground service.
2. I kill the app.
3. And I walk to see whether the stream is updating or not.
4. It is updating but at the same time, it is throwing me the error.

Is this supposed to happen?

**Comment by Dev-hwang** [comment]
https://github.com/objectbox/objectbox-dart/commit/e61ea42c8c0a2826342339b976c129f1b3390c5f

I tested with the above file and there was no problem.
It may be a BroadcastStream problem, so can you try adding `onCancel` as below?

```dart
final _stepCountStream =
    Stream<StepCount?>.periodic(const Duration(seconds: 10))
        .asBroadcastStream(onCancel: (subscription) => subscription.cancel());
```

**Comment by darshansatra1** [comment]
I tried this but nothing changed. I think there is some issue with flutter.
