### ISSUE TITLE
Blank White Screen When Opening Closed App

### ISSUE THREAD

**Issue by JonathanLam12345** [Dev-hwang/flutter_foreground_task#110]
When running the sample project, if you close the app and open the app either by selecting the notification or selecting the app on your device home screen, the app will display a blank white screen.

**Comment by Dev-hwang** [comment]
Can I see a detailed scenario and a screen where the error occurred?

**Comment by JonathanLam12345** [comment]
@Dev-hwang 

When the notification is pressed the function `onNotificationPressed()` will execute while the app is reopened and then `sendPort?.send('onNotificationPressed');` get executed, but sometimes FlutterForegroundTask.launchApp("/resume-route"); will get executed. I guess it is because the app is not fully opened up yet and this will cause the app screen to have a blank white screen.

**Comment by JonathanLam12345** [comment]
I found this StackOverflow post that seems to have the same issue as me:
https://stackoverflow.com/questions/73191762/production-build-from-play-store-only-shows-white-screen

**Comment by kkondarev** [comment]
Yep, I am the author of the above mentioned post. I also filed a issue in flutter itself (further setup and config data there), however it got closed with the following explanation: "Since this involves issues with a combination of third-party, we are unfortunately not sure how to resolve this issue".
https://github.com/flutter/flutter/issues/109100

**Comment by LorenzSchueler** [comment]
I'm facing the same issue. Any updates?

**Comment by JonathanLam12345** [comment]
@LorenzSchueler This issue has already been resolved. Make sure you are using the latest package version.

**Comment by LorenzSchueler** [comment]
@JonathanLam12345 I'm using the latest version `6.0.0+1`
