### ISSUE TITLE
Android 13 support.

### ISSUE THREAD

**Issue by AmanMasipeddi** [Dev-hwang/flutter_foreground_task#113]
Hi,

I couldn't find "Discussions", so I am posting it here. I am just wondering if this plugin supports Android 13. Right now, it is not working for Android 13. 

Thank you :)

**Comment by stavgafny** [comment]
Working fine on my android 13 pixel on debug and release.

**Comment by Dev-hwang** [comment]
Please tell me how it doesn't work. If an error occurs, please capture the error in debug mode.

**Comment by AmanMasipeddi** [comment]
Thank you for your reply. I will get back to you on this.
