### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by typexy** [Dev-hwang/flutter_foreground_task#118]
When using flutter_foreground_task for android as described in combination with another plugin (which is written in native code, too) I do receive the following error message as soon as onStart() is called:
MissingPluginException(No implementation found for method xxx on channel yyy)

The plugin is working when called regularly on main function.

Is there anything I can do to make it work with this plugin?

**Comment by AliEasy** [comment]
For flutter 3.0.0 and later:
Use the following code in `onStart` method
`DartPluginRegistrant.ensureInitialized();`

For flutter prior to version 3.0.0 you have to register the plugin manually
