### ISSUE TITLE
How to use receivePort with WillStartForegroundTask

### ISSUE THREAD

**Issue by gmkado** [Dev-hwang/flutter_foreground_task#119]
Is there a recommended way to retrieve the `ReceivePort` when using `WillStartForegroundTask`?

It looks like the `FlutterForegroundTask.receivePort` property is only valid when the service is running.  When using `WillStartForegroundTask` the service start/stop is handled according to lifecycle events so we don't really know when to retrieve it.  I could also subscribe to lifecycle events and retrieve it then, but that seems messy and order dependent.  

It would be nice if instead we could pass a listen callback to `WillStartForegroundTask` widget that gets listened to when the service is started.

**Comment by kmemo** [comment]
For me placing the following in `onWillStart: () async {...}` of `WillStartForegroundTask` worked:

`  if (Platform.isAndroid && (! await FlutterForegroundTask.canDrawOverlays)) {`
`    //No permission`
`    return false;`
`  }`
`  final receivePort = FlutterForegroundTask.receivePort;`
`  if (context.mounted) {`
`    registerReceivedFgTaskPort(context, receivePort);`
`  }`
`  return true;`

If this is correct, the example of Readme file should include the above.
