### ISSUE TITLE
Doesn't call onDestroy on restart

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#12]
I want to do some operations when the service stops. When the service is stopped in the app onDestroy function works properly. But when I restart my device the onDestroy function is not called. Am I missing something here? or is it just the way services are?

**Comment by Dev-hwang** [comment]
`onDestroy` only works when `FlutterForegroundTask.stop()` is called.

**Comment by darshansatra1** [comment]
So when the onDestroy function code is running, can I start the service inside the function or it'll throw an error?

**Comment by Dev-hwang** [comment]
Restarting the service in the `onDestroy` func seems difficult. 
The `onDestroy` func only works with `FlutterForegroundTask.stop()` calls. 
There is no way to catch the event when the service is forcibly stopped or the app crashes.

**Comment by Dev-hwang** [comment]
Try to avoid exceptions as much as possible. I'll check to see if there are any exceptions.

**Comment by Dev-hwang** [comment]
Restarting the service in the onDestroy func seems difficult. Try to avoid exceptions as much as possible. I'll check to see if there are any exceptions.

**Comment by darshansatra1** [comment]
So we can start the service, right?

**Comment by Dev-hwang** [comment]
no. Impossible now. I'm going to try an implementation so that if the service is forcibly shut down, it can be restarted.

**Comment by Dev-hwang** [comment]
Upgraded plugins so that services can be restarted in case of unexpected problems. However, if the user forcibly terminates the service or the problem that continues to occur, it may not work because the event cannot be caught.

**Comment by darshansatra1** [comment]
Thank you for the update
