### ISSUE TITLE
"attach" to a running foreground_task when we restart an application

### ISSUE THREAD

**Issue by gri38** [Dev-hwang/flutter_foreground_task#120]
Hello.
I don't know if I'm describing a bug or just a question (but I don't know how to ask a question other than by submitting an issue ;-))

Here is my usage of the lib:
- I start my app, which starts a foreground task.
- I close my app with "close all" on android: all apps are closed.
- The foreground task continues, and that is expected: great.
- When I start again the application (not from the notification: from its icon launcher (on android), I would like to detect the foreground_task is already running, and to attach to its receivePort BUT:
  - when I start, `await FlutterForegroundTask.isRunningService` returns `false`
  - Even if I init the task before.

=> How can I do to know a foreground task is running when I start my app ?

Thanks a lot.

**Comment by fidelisakilan** [comment]
I have similar issue, after app restart the _isRunningService still says false even when the service is saying

**Comment by gri38** [comment]
I finally manage to handle that. I write here how I did:

I get the running state at app startup:
await FlutterForegroundTask.isRunningService.

If it returns false, I start the foreground task as explained in the doc.
If it returns true: my foreground task is already running, and I attach to it like that:
 - I don't call _initForegroundTask
 - I call _startForegroundTask but with those modifications compared to the doc:
   - I **DON'T** call restart service:
   
![image](https://user-images.githubusercontent.com/26554495/217523827-62811855-98db-4d55-a2b9-b510277a795d.png)

- in _registerReceivePort I **DON'T** call _closeReceivePort();
