### ISSUE TITLE
Foreground execution iOS not start

### ISSUE THREAD

**Issue by fabiototh** [Dev-hwang/flutter_foreground_task#127]
After 15-30 seconds iOS cancels the background. However, a Timer on onStart is not executed after 1 minute.
How do I run a timer in foreground using package on iOS?

`Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
      periodicTimer = Timer.periodic(const Duration(minutes: 1), (_) {
    // something
}
}`

**Comment by Johnnyfdev** [comment]
Same problem here

**Comment by fabiototh** [comment]
On iOS for some reason it only periodically runs events that are shorter than 30 seconds.
I switched the Timer to a StreamSubscription and it also worked better.
