### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences

### ISSUE THREAD

**Issue by SaulArriaga** [Dev-hwang/flutter_foreground_task#130]
I am getting "(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences" as trying to set any value by using

I have tried with:
dependency_overrides:
  shared_preferences_ios: 2.1.1

but it doesn't work.

Flutter Doctor:

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale es-419)
    • Flutter version 3.3.10 on channel stable at /Users/saul/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/saul/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPad (mobile)   • eef26d8e2a4a3dd159a4105b675bea927ab5300a • ios            • iOS 12.5.5 16H62
    • macOS (desktop) • macos                                    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by SchokoShake** [comment]
Having the same problem. Downgrading shared_preferences to 2.0.15 solved the problem for now. Newer versions of the shared_preferences rely on shared_preference_foundation instead of shared_preference_ios which dropped the getAll method. This change is not yet reflected for this plugin.

**Comment by SaulArriaga** [comment]
Thanks @SchokoShake, downgrading to version 2.0.15 solved the problem.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/118401 and #131

**Comment by Kurogoma4D** [comment]
I've confirmed it's working with `flutter_foreground_task 4.0.1` with `shared_preferences 2.0.17` , so it seems can be closed.
