### ISSUE TITLE
Single event triggers onNotificationPress() of multiple apps with flutter_foreground_task

### ISSUE THREAD

**Issue by kmemo** [Dev-hwang/flutter_foreground_task#137]
Hi, I have created two Android apps that utilizes flutter_foreground_task v4.1.0 (Flutter 3.7.3).

While both app are running in background on an Android device, tapping either of notification seems to trigger onNotificationPress() of **both** apps and the both apps end up showing ResumeRoutPage(). The app that was put to the background last seems to be get shown as the front most app with a higher provability but it is not always the case.

Am I missing something in setting up the plugin??

In getPendingIntent method of ForegroundService.kt (flutter_foreground_task version 4.1.0), Intent is declared as:
   Intent(ACTION_NOTIFICATION_PRESSED).
Would it be possible to append unique uri to the Intent so that received Intents can be filtered at the receiving end?

**Comment by boyd-boyd** [comment]
@kmemo  
can you tell me how you are starting the service, I'm not able to get the service  started, the startservice is returning false every single time, the example is also not working in my case, could you post the service started code in the reply. 
for more info about my issue you can check at : https://github.com/Dev-hwang/flutter_foreground_task/issues/141

I'm really sorry for asking about my issue here, but i can't find any way to get it running.
