### ISSUE TITLE
API 33

### ISSUE THREAD

**Issue by jalys** [Dev-hwang/flutter_foreground_task#142]
hello all 

I am new to this plugin, 
I just tested the example file on a API 33 emulator, and i get no notification in the top bar after launching the task ( same on my phone )

**// got solution :** 
I switch the min sdk to 32 an it works fine ... ( as it was 33 ) 

thanks all.

**Comment by blopker** [comment]
Just figured this out. API 33 needs an additional permission for notifications: https://developer.android.com/develop/ui/views/notifications/notification-permission

Basically add `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` to your manifest file along with the other permissions this plugin needs. This should probably get added to the readme.

**Comment by razfazz** [comment]
> hello all
> 
> I am new to this plugin, I just tested the example file on a API 33 emulator, and i get no notification in the top bar after launching the task ( same on my phone )
> 
> **// got solution :** I switch the min sdk to 32 an it works fine ... ( as it was 33 )
> 
> thanks all.

are you sure you are talking about the minsdk or the targetsdk?

**Comment by hwj930513** [comment]
release version ^4.2.0

you will need to add the information below to use this version.

/android/app/build.gradle
```gradle
defaultConfig {
  targetSdkVersion 33 // need bump
}
```

/android/app/src/main/AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" /> <!-- for Android 13 -->
```
