### ISSUE TITLE
Can I use this package to upload files in foreground service?

### ISSUE THREAD

**Issue by khayargoli** [Dev-hwang/flutter_foreground_task#145]
My app uploads large files to server, can I use this service to use foreground service on demand when I am trying to upload file, and then close the service when it successfully uploads?

Thanks

**Comment by Dev-hwang** [comment]
I haven't tested it, but it seems possible.

```dart
@override
Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
  // upload file..

  // close service
  FlutterForegroundTask.stopService();
}
```
