### ISSUE TITLE
Not Requesting Notification Permissions on SDK 31, 32, or 33

### ISSUE THREAD

**Issue by cottonnj** [Dev-hwang/flutter_foreground_task#146]
I feel like I am missing an important step but is has become extremely frustrating.  I am having a similar issue to #142.  I can use the example project and everything works perfectly.  I am having issues integrating it into my current app.  So I stepped back and created a new project and added the example main in then modified the manifest and build.gradle as instructed hoping to be able to create a working project from scratch but no matter what I do it does not prompt for Notifications permission when start is pressed.  I have tried building for SDK 31, 32 and 33.  I have added the:

 <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
 
 Just incase that is the issue all with no luck.  It seems there is another step to add to some file somewhere to allow this to work.  The two main files are identical and there are very little differences to the manifest and gradle files.  Is there somewhere else to look that isn't described in the readme that I am missing?  I have done a diff on the directories but nothing stands out, however there are a lot of little nuances between the directories to make it difficult to find actual changes.  Can anyone else build a project from scratch and add the main.dart file and get it to run?  

I am running this on a Samsung S22 Ultra with Android 13.

Thanks in advanced.

**Comment by hwj930513** [comment]
release version ^4.2.0

you will need to add the information below to use this version.

/android/app/build.gradle
```gradle
defaultConfig {
  targetSdkVersion 33 // need bump
}
```

/android/app/src/main/AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" /> <!-- for Android 13 -->
```

**Comment by luohao123** [comment]
android:exported needs to be explicitly specified for element <receiver#com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
