### ISSUE TITLE
MissingPluginException(No implementation found for method getUsersInfo on channel

### ISSUE THREAD

**Issue by a1239897580** [Dev-hwang/flutter_foreground_task#149]
Problem description: After starting the front-end service, the native platform channel cannot be accessed
Problem details: After starting the front-end service, my platform channel seems to have failed, and I am unable to call platform methods, prompting an error as shown in the title. I checked similar problems in the problem list, for example, calling DartPluginRegister.ensureInitialized() in onStart; It didn't solve my problem.
Flutter version: 3.3.10
Plugin version: Flutter_ foreground_ task 4.1.0
I am running sample code

**Comment by hoyo00** [comment]
When starting a foreground service from the background, the app does not create an `Activity`.

Therefore, the app does not call it from `onCreate` of the `Activity` class.

Initialize the MethodChannel in the `configureFlutterEngine` function instead of the `onCreate` function.

```kotlin
class MainActivity : FlutterFragmentActivity(), MethodCallHandler {
    private lateinit var methodChannel: MethodChannel

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        val binaryMessenger = flutterEngine.dartExecutor.binaryMessenger

        GeneratedPluginRegistrant.registerWith(flutterEngine)
        methodChannel = MethodChannel(binaryMessenger, "com.example.test.method")
        methodChannel.setMethodCallHandler(this@MainActivity)
    }

    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
        // methodChannel = MethodChannel(binaryMessenger, "com.example.test.method")
        // methodChannel.setMethodCallHandler(this@MainActivity)
    }
}
```

**Comment by pamafe1976** [comment]
I have the same problem

**Comment by ammaraldirawi** [comment]
Did you guys found a salutation or a work around?  I have the same issue.
I think the issue is that s MethodChannel is not compatable with the flutter background service

**Comment by deakjahn** [comment]
First, you need at least Flutter 3.7 in order to use background channels from isolates (which is quite old now, so it shouldn't be a problem, but 3.3 was already outdated even back in May). Second, you need to have the channel set up on the platform side as well. Are you sure it's up and running? It doesn't need to be in a third-party plugin, it can be in your own platform code.

**Comment by deakjahn** [comment]
@Dev-hwang However, there's another, related problem. While the above works for any outside plugin that you call from your app, it doesn't work for a plugin that's **inside** your app. And I spent a day or so to find out why, without success so far—I fail to see what might be that different depending on whether the plugin is inside or outside. As you use quite a few tricks when setting up the `ForegroundService`, you might happen to have an idea, I hope. I attach a small repro, the usual Flutter template with your plugin added, the FAB starts the service and tries to call the platform on startup. This doesn't get through while the normal call earlier, not yet from the service, does.

As you can see, it does call `BackgroundIsolateBinaryMessenger.ensureInitialized()` (and the other two, commented out, no matter how you experiment with those, they don't help). Being an internal plugin, it doesn't get listed in `GeneratedPluginRegistrant`, so it's added manually from `MainActivity`. In all other respects, it's a correct, standard, well-behaving plugin.

[foreground_test.zip](https://github.com/Dev-hwang/flutter_foreground_task/files/13772404/foreground_test.zip)

**Comment by n305225282** [comment]
I had the same problem. When the service starts, the "onAttachedToEngine" of the other plugin is called. Later, when the service stops, the "onDetachedFromEngine" of the other plugin is called. Later, a MissingPluginException will occur when you try to use a detached plugin

**Comment by deakjahn** [comment]
If you use the up-to-date Flutter version, 3.7 or later, it works out of the box. The only problem I can find is, as I described above, if you try to use an internal plugin in your own app. Using the usual, external plugins seems to work just fine.

I'm investigating the internal problem actively, though, because I need it very much.

**Comment by deakjahn** [comment]
@n305225282 I went straight to the Flutter Discord channel where the actual framework and engine developers hang out (https://discord.com/channels/608014603317936148/608021010377080866/1189518790829023272, https://discord.com/channels/608014603317936148/608021234516754444/1189347409206202458) and started to enumerate what I have already found out.

As I can see it now, but this is very much a moving target, our foreground services _are not_ background isolates as far as the Flutter engine is concerned. This means (as I also found this while experimenting) that `BackgroundIsolateBinaryMessenger.ensureInitialized()` isn't even required, it doesn't make any difference actually, calling from the service doesn't use the `BackgroundIsolateBinaryMessenger` at all, it uses the regular, non-background channel mechanism instead.

If this still works this way, well, it's more or less irrelevant for the users of the plugin, of course. What I still struggle with is my internal plugin that I couldn't yet make function through the channel.

**Comment by deakjahn** [comment]
@n305225282 The reason was, very probably, successfully identified by one of the Flutter developers, so I'll start modifying this plugin to add the required steps. It should become a PR in the end.

But this only applies to the communication to your own platform code inside the app. Simply using plugins from your foreground service already works without issues.

**Comment by Dev-hwang** [comment]
check [flutter_foreground_task_example](https://github.com/Dev-hwang/flutter_foreground_task_example/tree/main/internal_plugin_service)
