### ISSUE TITLE
Ton of Kotlin errors after updating from `2.0.5` to `2.2.0`

### ISSUE THREAD

**Issue by TheLastGimbus** [Dev-hwang/flutter_foreground_task#15]
Hi there!

After update, I got ton of some "redeclaration" (and other) Kotlin errors

Luckly, I was able to solve them with:
```bash
# in my app directory
flutter clean
cd android
./gradlew clean

cd ..
flutter pub get
flutter run
# Yay it works!
```

Also in `android/build.gradle` i updated `ext.kotlin_version` to `'1.5.10'`, but it was for other plugins so it may not be required for `foreground_task`

I'm leaving this here in case someome has this issue too (dunno if I should close it right ahead or leave it open :shrug:)

**Comment by Dev-hwang** [comment]
This can happen with any plugin. This happens especially often when trying to upgrade plugins. Most of these problems can be solved by entering the `flutter clean` command for problems with the cache remaining locally.

Thank you @TheLastGimbus. It's okay to keep this issue open as there may be someone suffering from this.
