### ISSUE TITLE
how to communicate with services with UI

### ISSUE THREAD

**Issue by luohao123** [Dev-hwang/flutter_foreground_task#150]
I want sending a value to services to control the service bahvior, how to do that>?

**Comment by h2210316651** [comment]
You can use shared preferences to communicate between the isolate and your main thread. If at all you're using map or other data you can use json.encode to save it as a string and then after retrieval use json.decode to convert it back to a map.

**Comment by luohao123** [comment]
@h2210316651  I need in main thread to invoke a method of service, if using prefs, I need inside services to for loop to check the value, and then assign, this obvisouly very energy consuming. It's should not be a good way to do it.

**Comment by h2210316651** [comment]
In such a case configure your foreground task receive port to recieve an event and use sendport from your main thread to send the event. On the isolate when an event is received invoke your method

**Comment by luohao123** [comment]
@h2210316651 thanks, any example code to do so

**Comment by h2210316651** [comment]
It's in the default example provided with the code. Please take a look.

**Comment by luohao123** [comment]
@h2210316651 am not using this lib, am using dart code directly sending the dart service to native foreground, I just need found a way to invoke my dart servie func in main thread, does there any bare code could do this?
