### ISSUE TITLE
 Unhandled Exception: PlatformException(NOTIFICATION_PERMISSION_REQUEST_CANCELLED, The dialog was closed or the request was canceled during a runtime notification permission request., null, null)

### ISSUE THREAD

**Issue by luohao123** [Dev-hwang/flutter_foreground_task#152]
Unhandled Exception: PlatformException(NOTIFICATION_PERMISSION_REQUEST_CANCELLED, The dialog was closed or the request was canceled during a runtime notification permission request., null, null)

**Comment by AmanMasipeddi** [comment]
I am also getting this exception when the app is pushed to background/killed.

**Comment by hoyo00** [comment]
Starting a foreground service on Android 13 and higher requires the notification permission. Request notification permission in the initState function.

**Comment by AmanMasipeddi** [comment]
@hoyo00 - can we handle this exception if user choose not to provide the permission?

**Comment by hoyo00** [comment]
@AmanMasipeddi 

`NOTIFICATION_PERMISSION_REQUEST_CANCELLED` exception cannot be directly handled, 

but `NotificationPermission.denied` result is returned from `FlutterForegroundTask.checkNotificationPermission()` or `FlutterForegroundTask.requestNotificationPermission()` function.

**Comment by AmanMasipeddi** [comment]
@hoyo00 thank you for the reply. But even when I grant the permission, this exception is being thrown after I open the app from background.

**Comment by hoyo00** [comment]
@AmanMasipeddi 

It seems to work fine with version 4.2.0. I'm using a new example.

**Comment by hoyo00** [comment]
@AmanMasipeddi 

The important thing is to allow permission on the widget and start the service.

**Comment by Dev-hwang** [comment]
@luohao123 @AmanMasipeddi

Would you like to upgrade to version 5.2.1?

**Comment by AmanMasipeddi** [comment]
@Dev-hwang Thank you so much for the update. I will try this and let you know here.

**Comment by luohao123** [comment]
please try le tme know

**Comment by MuhammadXr** [comment]
Hii think I found the solution
Programm worked fine when I asked permission in main.dart file. Try this

**Comment by MuhammadXr** [comment]
> please try le tme know

👌
