### ISSUE TITLE
error when starting foreground service in background: PlatformException(ACTIVITY_NOT_ATTACHED, Cannot call method using Activity because Activity is not attached to FlutterEngine., null, null)

### ISSUE THREAD

**Issue by Mrbluesky-ai** [Dev-hwang/flutter_foreground_task#153]
Hello there,
I Get this error when starting up a foreground service in the background:
`PlatformException(ACTIVITY_NOT_ATTACHED, Cannot call method using Activity because Activity is not attached to FlutterEngine., null, null)`
Is there a way to fix this?

**Comment by hoyo00** [comment]
you seem to have used a function that is not available in the background (with no app screen).

functions that can only be used in the foreground state are as follows:
```dart
FlutterForegroundTask.checkNotificationPermission();
FlutterForegroundTask.requestNotificationPermission();
FlutterForegroundTask.minimizeApp();
FlutterForegroundTask.setOnLockScreenVisibility(true);
FlutterForegroundTask.openSystemAlertWindowSettings();
FlutterForegroundTask.requestIgnoreBatteryOptimization();
FlutterForegroundTask.openSystemAlertWindowSettings();
```
i think the owner should update the docs.

**Comment by Dev-hwang** [comment]
It seems that this problem occurs when checking the notification permission. I will fix the problem and release the next version.

**Comment by Mrbluesky-ai** [comment]
Release 5.2.1 fixed the problem, thanks!
