### ISSUE TITLE
PlatformException ACTIVITY_NOT_ATTACHED

### ISSUE THREAD

**Issue by busslina** [Dev-hwang/flutter_foreground_task#156]
I receive this error when trying to init & start foreground service from a scheduled alarm.

I readed that it is possible in Android to do that. Maybe it would be also possible with this library with some changes. I am asking.

**Comment by Dev-hwang** [comment]
It seems that this problem occurs when checking the notification permission. I will fix the problem and release the next version.

**Comment by busslina** [comment]
Thank you

**Comment by Dev-hwang** [comment]
Would you like to upgrade to version 5.2.1?

**Comment by busslina** [comment]
Thank you. Now it works okay (only on emulator device, not on my phone, but this is not your lib issue).

Do you know why some phones do not allow to start from background? Is there any way to achieve this?

**Comment by Dev-hwang** [comment]
yes. there is already a way to enable that option.

### :lollipop: canDrawOverlays (Android)

Returns whether the "android.permission.SYSTEM_ALERT_WINDOW" permission was granted.

```dart
Future<bool> function() => FlutterForegroundTask.canDrawOverlays;
```

### :lollipop: openSystemAlertWindowSettings (Android)

Open the settings page where you can allow/deny the "android.permission.SYSTEM_ALERT_WINDOW" permission.

> **Warning**
> It only works when the app is in the foreground.

```dart
Future<bool> function() => FlutterForegroundTask.openSystemAlertWindowSettings();
```

just call the code below and allow permission. it would be better if you explain to the user why you need to grant the permission before requesting the permission.

```dart
if (!await FlutterForegroundTask.canDrawOverlays) {
  await FlutterForegroundTask.openSystemAlertWindowSettings();
}
```

**Comment by busslina** [comment]
Thank you. I saw other package of you (https://github.com/Dev-hwang/permission_request_page). Is it well tested?. For now I'm using [permission_handler](https://pub.dev/packages/permission_handler) for handling permissions
