### ISSUE TITLE
How to send data inside task to main thread?

### ISSUE THREAD

**Issue by luohao123** [Dev-hwang/flutter_foreground_task#158]
Hello, there is a sendPort in prams, but I using sendPort to send data to main thread (trying), don't know how to receive in main thread, any thoughts? this part is unclear for new comer users

**Comment by Dev-hwang** [comment]
try example https://pub.dev/packages/flutter_foreground_task/example

Register ReceivePort before starting the service. You can listen to data through the listen function of ReceivePort.

```dart
Future<bool> _startForegroundTask() async {
  // Register the receivePort before starting the service.
  final ReceivePort? receivePort = FlutterForegroundTask.receivePort;
  final bool isRegistered = _registerReceivePort(receivePort);
  if (!isRegistered) {
    print('Failed to register receivePort!');
    return false;
  }

  if (await FlutterForegroundTask.isRunningService) {
    return FlutterForegroundTask.restartService();
  } else {
    return FlutterForegroundTask.startService(
      notificationTitle: 'Foreground Service is running',
      notificationText: 'Tap to return to the app',
      callback: startCallback,
    );
  }
}

bool _registerReceivePort(ReceivePort? newReceivePort) {
  if (newReceivePort == null) {
    return false;
  }

  _closeReceivePort();

  _receivePort = newReceivePort;
  _receivePort?.listen((data) {  // <-- here
    if (data is int) {
      print('eventCount: $data');
    } else if (data is DateTime) {
      print('timestamp: ${data.toString()}');
    }
  });

  return _receivePort != null;
}
```

**Comment by luohao123** [comment]
@Dev-hwang  I just tried this one, it worked!

NOW, I HAVE one further question: How to make the sql update signal be aware to the main thread.

**Comment by Dev-hwang** [comment]
You just need to notify the main isolate using sendPort if the data save is successful in TaskHandler.

Communication between isolates in this plugin is only possible with sendPort. (TaskHandler -> main isolate)

**Comment by luohao123** [comment]
@Dev-hwang  Thank u !! Now I think I compose a solution to run a p2p messageing service in foreground even the apps killed or in background.

Now, wanna further ask, does this will consume too much mem? And the apps always have a notification banner in noti center, this might make some users uncomfortable, is there a way to make it not such obvious for users?

**Comment by Dev-hwang** [comment]
A foreground service is literally a service that is visible to the user. It is the longest-lived service on the Android platform. Therefore, battery usage is higher than other services, and notifications cannot be hidden.

**Comment by KyungRyul** [comment]
As opposed to ReceivePort , how do I send data or signal from foreground to background?

**Comment by hoyo00** [comment]
@KyungRyul 

Currently there is no way. However, you can use the following functions to save data before starting the service and get data through the get function in TaskHandler.

```dart
Future<bool> _startForegroundTask() async {
  // You can save data using the saveData function.
  await FlutterForegroundTask.saveData(key: 'customData', value: 'hello');

  return FlutterForegroundTask.startService(
    notificationTitle: 'Foreground Service is running',
    notificationText: 'Tap to return to the app',
    callback: startCallback,
  );
}

class MyTaskHandler extends TaskHandler {
  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    // You can use the getData function to get the stored data.
    final customData =
        await FlutterForegroundTask.getData<String>(key: 'customData');
    print('customData: $customData');
  }
}
```

**Comment by KyungRyul** [comment]
> 

thank you!

**Comment by KyungRyul** [comment]
@hoyo00 
thank you !

**Comment by dudizimber** [comment]
@KyungRyul you can also create a ReceivePort inside the `onStart` function like so: 

``` 
  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) {
    _sendPort = sendPort;

    final receivePort = ReceivePort();

    sendPort!.send({
      'method': 'setSendPort',
      'port': receivePort.sendPort,
    });
}
```

Then you can retrieve back the `SendPort` in the main thread like so:

```
_receivePort?.listen((message) {
 if (message is Map) {
      if (message['method'] == 'setSendPort') {
          final remotePort = message['port'];
      }
    } 
}
```

And with it, you can send data to the isolate more easily.

**Comment by luohao123** [comment]
I am sorry, the previous usage it proofed to be wrong.

I have to using WillStartForegroundTask

which **start the services** only when app goes to background.


But I have some question about this

**Comment by shawsa-artc** [comment]
> TaskHandler

How can i pass a class / object through sendport? is it possible?

**Comment by yileijiang** [comment]
> @KyungRyul you can also create a ReceivePort inside the `onStart` function like so:
> 
> ```
>   @override
>   Future<void> onStart(DateTime timestamp, SendPort? sendPort) {
>     _sendPort = sendPort;
> 
>     final receivePort = ReceivePort();
> 
>     sendPort!.send({
>       'method': 'setSendPort',
>       'port': receivePort.sendPort,
>     });
> }
> ```
> 
> Then you can retrieve back the `SendPort` in the main thread like so:
> 
> ```
> _receivePort?.listen((message) {
>  if (message is Map) {
>       if (message['method'] == 'setSendPort') {
>           final remotePort = message['port'];
>       }
>     } 
> }
> ```
> 
> And with it, you can send data to the isolate more easily.

I was looking for a way to do this for ages! This solution worked perfectly for me. Thank you!
