### ISSUE TITLE
Conflict with audio_service

### ISSUE THREAD

**Issue by BecoStopclub** [Dev-hwang/flutter_foreground_task#16]
Hi, first thanks for this great library.
I am having the following issue.

When I call <code>FlutterForegroundTask.stop();</code>

[audio_service](https://pub.dev/packages/audio_service) also stops its service, the opposite does not happen.

I looked and they both use different serviceId.
<code>flutter_foreground_task: 1000</code>
<code>audio_service: 1124</code>

Any suggestions on what it might be?

**Comment by marcusvpais** [comment]
Im also having this problem.

**Comment by Dev-hwang** [comment]
Sorry, I was late to answer because I had a busy schedule.

I'm not familiar with the `audio_service` plugin. Can you be more specific about the circumstances in which the problem occurs? And I want to know where and when to call `FlutterForegroundTask.start` and `FlutterForegroundTask.stop()`.

**Comment by BecoStopclub** [comment]
I'm closing the issue.

The bug is related to agora.io, not <code>flutter_foreground_task</code> or even <code>audio_service</code>.
