### ISSUE TITLE
launchApp() function doesn't navigate to the route

### ISSUE THREAD

**Issue by MarkisDev** [Dev-hwang/flutter_foreground_task#160]
Hey, the launchApp() function doesn't seem to navigate to the mentioned route if the app is in the background (recently used apps). It just launches the app in the previously used route.

When I clear the app from recently used, then it opens the app in the specified route.

I'm testing on Android.

Is this intended or is there a way to ensure the app goes to the new route in all cases?

**Comment by MarkisDev** [comment]
Sorry I know how to get around this now.
If anyone is wondering, you can navigate to a new route by passing a message from isolate to main (like how it's done for onNotificiationPressed())

Thanks for this amazing package!

**Comment by deveshm** [comment]
I'm not sure why the old code that uses isolate (sendPort) was removed from the documentation, but I needed to look at the old documentation page to find it and use it for this purpose: https://pub.dev/packages/flutter_foreground_task/versions/4.2.0
