### ISSUE TITLE
onDestroy is not triggered when app is force stopped. 

### ISSUE THREAD

**Issue by arpitkushwaha** [Dev-hwang/flutter_foreground_task#161]
Steps to reproduce:-

1. Start the service.
2. Kill the app.
3. Observe that the notification is visible, i.e., the service is running; hence, its code should also execute along with all the callbacks.
4. Go to the app settings and click on force stop.
5. Observe that the notification is removed now i.e. service is killed. Hence, the onDestroy callback should get triggered but it is not.

**Comment by hoyo00** [comment]
I'm not sure either... I know that Android platform policy is correct behavior that if a service is killed by the user or the system, it will not be restarted.

**Comment by arpitkushwaha** [comment]
@hoyo00 Thanks for the reply. I don't expect it to restart. But I am expecting to get a callback in the onDestroy() method of TaskHandler whenever the service is stopped, For ex. when the app is force stopped due to which service gets killed. 

Normally when I open the app and stop the service I get the callback and it works fine and as expected. But when the app is force-stopped (service gets killed), I don't get any callback.

**Comment by hoyo00** [comment]
@arpitkushwaha 

If the service is not restarted, it means that the onDestroy function is not called.

For this plugin, the `onDestroy` function in the foreground service should be called before TaskHandler's `onDestroy` function should be called.

```kotlin
	override fun onDestroy() {
		super.onDestroy()
		stopForegroundTask() // this
		stopForegroundService()
		unregisterBroadcastReceiver()
		if (foregroundServiceStatus.action != ForegroundServiceAction.STOP) {
			if (isSetStopWithTaskFlag()) {
				exitProcess(0)
			} else {
				Log.i(TAG, "The foreground service was terminated due to an unexpected problem.")
				if (notificationOptions.isSticky) {
					if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
						if (!ForegroundServiceUtils.isIgnoringBatteryOptimizations(applicationContext)) {
							Log.i(TAG, "Turn off battery optimization to restart service in the background.")
							return
						}
					}
					setRestartAlarm()
				}
			}
		}
	}

	private fun stopForegroundTask() {
		stopRepeatTask()

		currFlutterLoader = null
		prevFlutterEngine = currFlutterEngine
		currFlutterEngine = null

		val callback = object : MethodChannel.Result {
			override fun success(result: Any?) {
				prevFlutterEngine?.destroy()
				prevFlutterEngine = null
			}

			override fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
				prevFlutterEngine?.destroy()
				prevFlutterEngine = null
			}

			override fun notImplemented() {
				prevFlutterEngine?.destroy()
				prevFlutterEngine = null
			}
		}
		backgroundChannel?.invokeMethod(ACTION_TASK_DESTROY, null, callback) // this
		backgroundChannel?.setMethodCallHandler(null)
		backgroundChannel = null
	}
```
