### ISSUE TITLE
InvokeChannel limitation

### ISSUE THREAD

**Issue by typexy** [Dev-hwang/flutter_foreground_task#17]
Hi @Dev-hwang , 
I'd like to spawn a foreground task with this plugin, which executes code with other plugins (e.g. flutter_beacon). When I do this, I receive errors like "MissingPluginException Method x not found in channel y".

Is this due to the fact, that foreground task runs in a separate isolate and as a result it is not possible to to call methodIncovate because it needs to run in "UIThread"? Is this an implicit limitation or is this only due to other plugins? (Guess it's answered in #10. 

Is there any possible workaround you can think of without moving away fro this plugin?

**Comment by Dev-hwang** [comment]
Try the `flutter clean` command. If you've upgraded the version of this plugin, it's most likely a local build cache issue.
