### ISSUE TITLE
The foreground notification appears on top every interval update

### ISSUE THREAD

**Issue by a7mdragab** [Dev-hwang/flutter_foreground_task#174]
Hello,
I want the foreground notification to be displayed in the notification bar only once at first and stay as it is until it is stopped.
In the interval callback, I will just play sound file
How to modify the notification behavior as this

**Comment by a7mdragab** [comment]
any advice?

**Comment by Dev-hwang** [comment]
@a7mdragab 

Do not call the updateService function in the onRepeatEvent function. The updateService function is used to change the current task or notification content.

```dart
  // Called every [interval] milliseconds in [ForegroundTaskOptions].
  @override
  void onRepeatEvent(DateTime timestamp, SendPort? sendPort) async {
    // FlutterForegroundTask.updateService(
    //   notificationTitle: 'MyTaskHandler',
    //   notificationText: 'eventCount: $_eventCount',
    // );

    // Just play sound..
  }
```
