### ISSUE TITLE
Isolates not starting on release mode

### ISSUE THREAD

**Issue by khaldrigo** [Dev-hwang/flutter_foreground_task#177]
I have those issues, my app is working only in debug mode, but when i see it in release, the ForegroundService simply don't start
is there anything i can do to fix it? I am already on latest version of the package

E/flutter (12086): [ERROR:flutter/runtime/dart_isolate.cc(667)] Could not resolve main entrypoint function.
E/flutter (12086): [ERROR:flutter/runtime/dart_isolate.cc(168)] Could not run the run main Dart entrypoint.
E/flutter (12086): [ERROR:flutter/runtime/runtime_controller.cc(422)] Could not create root isolate.
E/flutter (12086): [ERROR:flutter/shell/common/shell.cc(614)] Could not launch engine with configuration.

**Comment by Dev-hwang** [comment]
The pragma annotation is missing. Please add an annotation to the startCallback as shown below.

```dart
@pragma('vm:entry-point') // forget
void startCallback() {
  FlutterForegroundTask.setTaskHandler(MyTaskHandler());
}
```
