### ISSUE TITLE
How to change a icon of notification on flutter-foreground-task

### ISSUE THREAD

**Issue by luanndm-dream** [Dev-hwang/flutter_foreground_task#178]
I don't no how to change a icon in a top-left of notification. I tried to find a way but.. nothing. Please help me!
 iconData: const NotificationIconData(
          resType: ResourceType.mipmap,
          resPrefix: ResourcePrefix.ic,
          name: 'launcher',
          backgroundColor: Color.fromARGB(255, 164, 255, 53),
        ),

**Comment by Roee-Tsur** [comment]
@luanndm-dream did you solve the issue somehow?
I'm facing the same problem :(

**Comment by Dev-hwang** [comment]
@luanndm-dream @Roee-Tsur 

Please try as below:

1. Open the `android` package.
![스크린샷 2023-11-09 오전 8 34 17](https://github.com/Dev-hwang/flutter_foreground_task/assets/47127353/10b04591-3b1a-4cb2-9651-0b3539976330)

2. Go to `res/drawable` and select Image Asset.
![스크린샷 2023-11-09 오전 8 58 38](https://github.com/Dev-hwang/flutter_foreground_task/assets/47127353/427f0226-e7ff-4c47-b6d1-880c55f2cff9)

3. Select the image you want and create a notification icon.
![스크린샷 2023-11-09 오전 8 59 03](https://github.com/Dev-hwang/flutter_foreground_task/assets/47127353/faebdd4c-75f9-49d6-abb4-e3e178a97e5f)
![스크린샷 2023-11-09 오전 8 59 28](https://github.com/Dev-hwang/flutter_foreground_task/assets/47127353/83b3f0e6-0423-471d-b429-c6c1eba657c0)

4. Create `NotificationIconData` as shown below.
```dart
const NotificationIconData(
    resType: ResourceType.drawable,
    resPrefix: ResourcePrefix.ic,
    name: 'star',
    backgroundColor: Colors.orange,
)
```

**Comment by Dev-hwang** [comment]
deprecated

move: https://github.com/Dev-hwang/flutter_foreground_task/blob/master/documentation/customize_notification_icon.md
