### ISSUE TITLE
Service stops when app is killed

### ISSUE THREAD

**Issue by aeropagz** [Dev-hwang/flutter_foreground_task#19]
As title says, the service is closed when the app is killed. Is this the right behavior? If so is there a way to prevent this?

**Comment by Dev-hwang** [comment]
The service works normally for actions that move to the background (back button, home button, screen off, remove from the list of recently launched apps, etc). But, service termination cannot be prevented by forcibly stopping the app in the processor manager or application information screen.

**Comment by jairusfdes** [comment]
I am trying something similar, but when i try to access the Pedometer package (https://pub.dev/packages/pedometer) in my task handler it doesn't work. the sensor event listeners are not registered . I don't see any errors in the logs.
If i call the pedometer from my app it works . but not if i put it in the handler . Is there some other setup for the Handler to be able to initate the pedometer package sensor ?
