### ISSUE TITLE
onNotificationPressed not trigger on v6.1.2

### ISSUE THREAD

**Issue by MR-14101-141** [Dev-hwang/flutter_foreground_task#194]
onNotificationPressed not trigger on v6.1.2

**Comment by Mrbluesky-ai** [comment]
I have the same issue, but only on android 14 with a higher kotlin version then the example app.
Does anyone have a solution for this?
@Dev-hwang ?

**Comment by Mrbluesky-ai** [comment]
I've discovered a temporary solution for this issue: you should set the target SDK to 33 in the `build.gradle`, while keeping the compile SDK at 34. This, for some reason, will resolve the problem.

**Comment by fbdesignpro** [comment]
This is probably unrelated but in my case an issue in `onRepeatEvent` was preventing triggers (#199)

**Comment by Dev-hwang** [comment]
@MR-14101-141 @Mrbluesky-ai 

Does the same problem occur in the latest version?
