### ISSUE TITLE
App icon is not being shown

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#2]
When I run the service and the task, the notification shows and updates properly. But the notification icon is a round white circle, how to I change it to my required icon.

**Comment by JayPerfetto** [comment]
I also suffer from this issue

**Comment by Dev-hwang** [comment]
> When I run the service and the task, the notification shows and updates properly. But the notification icon is a round white circle, how to I change it to my required icon.

The plugin version has been upgraded. You can customize the icon using the `icon` field.
```yaml
dependencies:
  flutter_foreground_task: ^1.0.9
```

1. Create icons by resolution using the `Image Asset` menu in Android Studio or the app icon creation plugin.
![스크린샷 2021-06-18 오전 10 16 41](https://user-images.githubusercontent.com/47127353/122491423-edabfd00-d01e-11eb-9a00-91eac847a8e3.png)
![스크린샷 2021-06-18 오전 10 17 40](https://user-images.githubusercontent.com/47127353/122491440-f4d30b00-d01e-11eb-941f-330244fea346.png)

2. Enter the icon name in the `NotificationOptions`.
```dart
  final flutterForegroundTask = FlutterForegroundTask.instance.init(
    notificationOptions: NotificationOptions(
      channelId: 'notification_channel_id',
      channelName: 'Foreground Notification',
      channelDescription: 'This notification appears when a foreground task is running.',
      channelImportance: NotificationChannelImportance.DEFAULT,
      priority: NotificationPriority.DEFAULT,
      icon: '@mipmap/ic_launcher',
    ),
    foregroundTaskOptions: ForegroundTaskOptions(
      interval: 5000
    )
  );
```
