### ISSUE TITLE
Plugin won't start, no build errors:

### ISSUE THREAD

**Issue by azzyloth** [Dev-hwang/flutter_foreground_task#205]
Hi I am getting no error but plugin is not starting and I am getting this log from flutter run --verbose:

 ] :flutter_foreground_task:processDebugJavaRes (Thread[Execution worker Thread 15,5,main]) started.
[        ] > Task :flutter_foreground_task:processDebugJavaRes NO-SOURCE
[        ] Skipping task ':flutter_foreground_task:processDebugJavaRes' as it has no source files and no previous output files.
[        ] :flutter_foreground_task:processDebugJavaRes (Thread[Execution worker Thread 15,5,main]) completed. Took 0.0 secs.
[        ] Resolve mutations for :flutter_foreground_task:bundleLibResDebug (Thread[Execution worker,5,main]) started.
[        ] Resolve mutations for :flutter_foreground_task:bundleLibResDebug (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
[        ] :flutter_foreground_task:bundleLibResDebug (Thread[Execution worker Thread 4,5,main]) started.
[        ] > Task :flutter_foreground_task:bundleLibResDebug
[        ] Caching disabled for task ':flutter_foreground_task:bundleLibResDebug' because:
[        ] Task ':flutter_foreground_task:bundleLibResDebug' is not up-to-date because:
 Output property 'output' file\build\flutter_foreground_task\intermediates\library_java_res\debug\res.jar has been removed.

[        ] :flutter_foreground_task:mergeDebugJniLibFolders (Thread[Execution worker Thread 13,5,main]) started.
[        ] > Task :flutter_foreground_task:mergeDebugJniLibFolders
[        ] Caching disabled for task ':flutter_foreground_task:mergeDebugJniLibFolders' because:
[        ] Task ':flutter_foreground_task:mergeDebugJniLibFolders' is not up-to-date because:
[        ]   Output property 'incrementalFolder' file \build\flutter_foreground_task\intermediates\incremental\mergeDebugJniLibFolders has been removed.
[        ]   Output property 'incrementalFolder' file \build\flutter_foreground_task\intermediates\incremental\mergeDebugJniLibFolders\merger.xml has been removed.
[        ]   Output property 'outputDir' file \build\flutter_foreground_task\intermediates\merged_jni_libs\debug\out has been removed.

any idea about this?

**Comment by fine-winner** [comment]
How did you resolve this since you marked it closed?
