### ISSUE TITLE
Crash on foregroundServiceType="connectedDevice"

### ISSUE THREAD

**Issue by mening12001** [Dev-hwang/flutter_foreground_task#222]
It seems that only foregroundServiceType="dataSync" is accepted. If I set foregroundServiceType to "connectedDevice", I receive the following exception:

java.lang.RuntimeException: Unable to create service com.pravera.flutter_foreground_task.service.ForegroundService: java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000010 in service element of manifest file
E/AndroidRuntime(12325): Caused by: java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000010 in service element of manifest file

Please participate, what could be the issue?

**Comment by Dev-hwang** [comment]
Does the same problem occur with the latest update?

**Comment by Dev-hwang** [comment]
move issue #226
