### ISSUE TITLE
Service could not gracefully restart 

### ISSUE THREAD

**Issue by erisanolasheni** [Dev-hwang/flutter_foreground_task#223]
Hello, good day.

We use flutter foreground service, to calculate user steps in the background and display them in a sticky notification.

The problem we are trying to tackle now is app stops working in the background after some time but retains the sticky foreground notification, hanging at "x" last counted steps before the stop. We have gotten these reports from quite a number of our users. After several debugs,  we think this happens when the operating system tries to free resources by restarting the foreground service. 

Do you have any advice on how to make flutter foreground service restart gracefully whenever the Operating System forces it to do so and continue whatever activity from where it stopped without any seizure?

**Comment by erisanolasheni** [comment]
Hello, any update on this?

**Comment by Dev-hwang** [comment]
hello try 7.4.2

**Comment by Dev-hwang** [comment]
Please update to the latest version and check.

**Comment by erisanolasheni** [comment]
I will do, thank, really appreciate!

**Comment by WingCH** [comment]
I noticed that the FOREGROUND SERVICE shuts down after running stably for around a day
I have an idea to use the Alarm Manager or Worker Manager to restart the Foreground Service, but I want to confirm if that is technically feasible. 
I am not familiar with Android, @Dev-hwang please for your help

**Comment by WingCH** [comment]
I discovered that this library has already implemented the use of Alarm Manager to restart the service:

https://github.com/Dev-hwang/flutter_foreground_task/blob/master/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/RestartReceiver.kt

**Comment by giandifra** [comment]
Hello, i've the same issue, how could i restart the service ? Thanks @Dev-hwang
