### ISSUE TITLE
Force Close App when start foreground with Android compileSdkVersion 31

### ISSUE THREAD

**Issue by pram507** [Dev-hwang/flutter_foreground_task#23]
### Force Close When Start Foreground with Android compileSdkVersion 31

hi i got force close when start the foreground service running on android emulator version Sv2
can u fix it.

Script

>    FlutterForegroundTask.init(
      androidNotificationOptions: const AndroidNotificationOptions(
        channelId: 'notification_channel_id',
        channelName: 'Foreground Notification',
        channelDescription: 'This notification appears when the foreground service is running.',
        channelImportance: NotificationChannelImportance.LOW,
        priority: NotificationPriority.LOW,
        iconData: NotificationIconData(
          resType: ResourceType.mipmap,
          resPrefix: ResourcePrefix.ic,
          name: 'launcher',
        ),
      ),
      iosNotificationOptions: const IOSNotificationOptions(
        showNotification: true,
        playSound: false,
      ),
      foregroundTaskOptions: const ForegroundTaskOptions(
        interval: 5000,
        autoRunOnBoot: true,
      ),
      printDevLog: true,
    );

**Android Log.**
> D/CompatibilityChangeReporter( 7017): Compat change id reported: 160794467; UID 10151; state: ENABLED
D/AndroidRuntime( 7017): Shutting down VM
E/AndroidRuntime( 7017): FATAL EXCEPTION: main
E/AndroidRuntime( 7017): Process: com.pramana507.cyclops_droid.dev, PID: 7017
E/AndroidRuntime( 7017): java.lang.RuntimeException: Unable to create service com.pravera.flutter_foreground_task.service.ForegroundService: java.lang.IllegalArgumentException: com.pramana507.cyclops_droid.dev: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime( 7017): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Flutter doctor**
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (2 available)

**Comment by Dev-hwang** [comment]
I have confirmed the problem. I'll let you know when it's resolved.

**Comment by Dev-hwang** [comment]
@pram507 

Try this!

Add the following line to your `pubspec.yaml` file.

```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: fix_IllegalArgumentException
```

Run the command.

```text
flutter clean
flutter pub get
```

**Comment by Dev-hwang** [comment]
@pram507 

Please update this plugin to 3.2.3 and try again.

```yaml
dependencies:
  flutter_foreground_task: ^3.2.3
```

**Comment by pram507** [comment]
nice close the issue, working now on android sdk 31
