### ISSUE TITLE
Dynamically change buttons

### ISSUE THREAD

**Issue by AhsanSarwar45** [Dev-hwang/flutter_foreground_task#230]
Hi, is it possible to dynamically change the buttons or their text? I am trying to implement a foreground notification for a timer, and I need to change the button label to 'pause' and 'resume' depending on the state.

**Comment by Dev-hwang** [comment]
@AhsanSarwar45

version 7.1.0

you can change buttons while the service is running.

```dart
FlutterForegroundTask.updateService(
  notificationButtons: [
    const NotificationButton(id: 'btn_bye', text: 'bye'),
  ],
);
```
