### ISSUE TITLE
Suggestion: Handling Exceptions for Foreground Services on Certain Android Versions

### ISSUE THREAD

**Issue by WingCH** [Dev-hwang/flutter_foreground_task#237]
We are encountering an issue where various foreground services, such as startForegroundService, fail for unknown reasons on some Android versions. This issue seems to be related to the restrictions mentioned in the official Android documentation: [Background work restrictions](https://developer.android.com/develop/background-work/services/foreground-services#bg-access-restrictions).

Specifically, we are encountering the ForegroundServiceStartNotAllowedException. If this exception is thrown, it would make debugging easier.

Here is an example code snippet demonstrating the issue:

// android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundServiceManager.kt
```kt
fun start(context: Context, arguments: Any?): Boolean {
    try {
        val nIntent = Intent(context, ForegroundService::class.java)
        val argsMap = arguments as? Map<*, *>
        ForegroundServiceStatus.setData(context, ForegroundServiceAction.START)
        NotificationOptions.setData(context, argsMap)
        ForegroundTaskOptions.setData(context, argsMap)
        ForegroundTaskData.setData(context, argsMap)
        NotificationContent.setData(context, argsMap)
        ContextCompat.startForegroundService(context, nIntent)
    } catch (e: Exception) {
        throw e // Added to facilitate debugging
    }

    return true
}
```

**Comment by Dev-hwang** [comment]
https://github.com/Dev-hwang/flutter_foreground_task/tree/feat-%23237

I added code to handle service request errors on dart side. will publish atfer testing

**Comment by Dev-hwang** [comment]
https://github.com/Dev-hwang/flutter_foreground_task/tree/feat-%23237

I added the code so that the developer can handle the service request error. will publish atfer testing

**Comment by WingCH** [comment]
Good! Thanks for your quick follow-up.

**Comment by Dev-hwang** [comment]
Please update to the latest version and check.
