### ISSUE TITLE
Start service from native side (Kotlin/Java)

### ISSUE THREAD

**Issue by TheLastGimbus** [Dev-hwang/flutter_foreground_task#24]
HI!
I would like to use a foreground service to update my native Android widget (on home screen) - I have everything set up and figured out, except the part "how to start foreground service with some Dart running when received `onUpdate` in widget"

Is there some nice `Intent` that I can just fire to start the service?

**Comment by Dev-hwang** [comment]
It seems difficult to implement that way using this plugin. You will probably have to implement it yourself and use it.

Here's the implementation I'm thinking of:

1. Get the `CallbackHandle` object using the `PluginUtilities.getCallbackHandle` function on the dart side and the `toRawHandle` function to get the raw value of the handler.

```dart
var rawValue = PluginUtilities.getCallbackHandle(callback)?.toRawHandle();
```

2. Use `MethodChannel` to send the raw value of the handler to the native side.

```dart
static const methodChannel = MethodChannel('your_package/method');

methodChannel.invokeMethod('setRawValue', rawValue);
```

3. Use `SharedPreferences` or `SQLite` in native to store the raw value of the handler.

4. Get the raw value of the handler saved above in the widget's `onUpdate` function.

5. Execute the dart side code using the `FlutterEngine.dartExecutor.executeDartCallback` function on the native side.

```kotlin
private fun executeDartCallback(callbackHandle: Long?) {
		// If there is no callback handle, the code below will not be executed.
		if (callbackHandle == null) return

		// If there is an already initialized foreground task, destroy it and perform initialization.
		if (currFlutterEngine != null) destroyForegroundTask()

		currFlutterEngine = FlutterEngine(this)

		flutterLoader = FlutterInjector.instance().flutterLoader()
		flutterLoader!!.startInitialization(this)
		flutterLoader!!.ensureInitializationComplete(this, null)

		val messenger = currFlutterEngine!!.dartExecutor.binaryMessenger
		backgroundChannel = MethodChannel(messenger, "flutter_foreground_task/background")
		backgroundChannel!!.setMethodCallHandler(this)

		val callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(callbackHandle)
		val appBundlePath = flutterLoader!!.findAppBundlePath()
		val dartCallback = DartExecutor.DartCallback(assets, appBundlePath, callbackInfo)
		currFlutterEngine!!.dartExecutor.executeDartCallback(dartCallback)
}
```

With this implementation, it seems that only the code on the dart side can be executed without running the foreground service. If I have time, I'll help you implement it.

**Comment by TheLastGimbus** [comment]
Yeah, what i ended up doing is exactly this 👌 Thanks for help!
