### ISSUE TITLE
NotificationButton For IOS

### ISSUE THREAD

**Issue by hassanali2596** [Dev-hwang/flutter_foreground_task#248]
I want to show NotificationButton in ios as it shown in android

**Comment by Dev-hwang** [comment]
@hassanali2596 

iOS Platform, `notificationButtons` is not displayed directly in notification.
When the user slides down the notification, the button is displayed, so you need to guide the user on how to use it.
https://developer.apple.com/documentation/usernotifications/declaring-your-actionable-notification-types
