### ISSUE TITLE
Process doesnt work after lock the screen

### ISSUE THREAD

**Issue by yassermohammad** [Dev-hwang/flutter_foreground_task#25]
Process doesnt work after lock the screen...

**Comment by Dev-hwang** [comment]
What are you doing with this plugin? Are you using other plugins to get data? Or do you simply update the notification?

It would be helpful to solve the problem if you tell me the type of operating system that is causing the problem and the implemented TaskHandler.

**Comment by Dev-hwang** [comment]
Could you please update the plugin to `3.4.0` and try again?

**Comment by Techno-Disaster** [comment]
@Dev-hwang on 3.7.3, was able to wakeup screen using wakeUpscreen but launchApp still fails. (tested both when terminated and in background)
