### ISSUE TITLE
8.2.0 doesn't compile

### ISSUE THREAD

**Issue by deakjahn** [Dev-hwang/flutter_foreground_task#253]
I really can't tell from the source code of the commit why but I can't compile 8.2.0, reverting back to 8.1.0 works.

Calling `FlutterForegroundTaskPlugin.addTaskLifecycleListener()` gives an _Unresolved reference_ error. Yes, the import is there:

    import com.pravera.flutter_foreground_task.*

and interestingly, `FlutterForegroundTaskLifecycleListener` resolves all right, from the same namespace. If I don't call the lifecycle static, the same reference in `GeneratedPluginRegistrant` will be the next unresolved reference.

Flutter is the latest, as always.

**Comment by Dev-hwang** [comment]
@deakjahn 

version 8.2.0, nothing changed other than lowering the minSdkVersion.

Try using the method below:

```text
Android Studio Menu > File > Invalidate Caches > Optional All check > Restart

and

run flutter command
> flutter clean
> flutter pub get
```

**Comment by deakjahn** [comment]
@Dev-hwang We're a bit past that, thanks. :-) It's not a cache issue because I can recreate it at will, both with the two versions from the usual Pub cache and from local copies. On the other hand, it could well be something specific to Android Studio that I work in, or a specific Gradle version, or whatever...

In addition to the actual minSdk change, you modified the source here and there to accommodate the 21-23 difference and also changed a couple of things in `PluginUtils.kt` (also modifying function signatures). So, I took parallel local copies of 8.1 and 8.2 and started to methodically restore file after file to see which one makes the error go away.

It wasn't a single file, I had to replace two: `ForegroundService.kt` and `PluginUtils.kt` for the first successful compilation, so I have to go further with the checks.

**Comment by Dev-hwang** [comment]
@deakjahn 

Did you find the cause of the problem?

```kotlin
import androidx.core.content.ContextCompat
```

Is it possible that the above class will cause problem?

**Comment by deakjahn** [comment]
No, I'm constantly banging my head into the wall while I'm pulling out my hair at the same time. :-D

It also seems that building from inside the IDE causes problems while building from the command line works. Also, I have two copies of your source files that, for all intents and purposes, only differ in tabs vs. spaces (I also checked with WinMerge, a very nice diff program) and one works, the other doesn't. Something *very* fishy here...

Having said that, I never had any similar issues with Android Studio, neither will all my other apps, neither with your module prior this last change. Absolutely insane... :-)

**Comment by Dev-hwang** [comment]
@deakjahn 

ok. I don't have a computer right now so I can't work. I'll revert the commit tomorrow and work again. :sob:

**Comment by deakjahn** [comment]
No, don't do that yet unless others also experience the same issue.

**Comment by deakjahn** [comment]
Right now, I'm struggling this this. We all saw that error many a time for sure:

```
* What went wrong:
Execution failed for task ':app:compileGoogleplayDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

I simply can't locate where that log is and reading the whole Internet did't provide an answer. Also, where to put `--stacktrace` or `--debug`? Some say Settings > Build > Gradle-Android Compiler > Options. Actually, the description there also says so. Only that there's no log anywhere I could find.

**Comment by deakjahn** [comment]
@Dev-hwang Rest assured, the disease in contagious, I can no longer compile the 8.1.0 either, now. :-)

I also tried to ask at https://stackoverflow.com/questions/78849727/how-to-diagnose-gradle-issues-in-flutter, we'll see. Don't revert it for the whole wide world, it's either something in my setup (although I have no idea what it could be) or we need Lt Columbo to investigate it.

**Comment by deakjahn** [comment]
@Dev-hwang It kinda solved itself, I wouldn't dare to say that I did. See over at SO for details. 8.2.0 works as well.
