### ISSUE TITLE
Foreground Task Doesn't Work on iOS

### ISSUE THREAD

**Issue by alperenbaskaya58** [Dev-hwang/flutter_foreground_task#257]
Hi,
We are trying to fetch data from API on interval given to Foreground task. Despite it shows as started, nothing happens on interval or sometimes. Perfectly works on android but we have tried --release mode on our real device iphone 14 pro nothing happens.
Only when user interacts with notification from foreground task it fires _onReceiveTaskData but it ends with count 3. Then no notification comes. 

We tried to reproduce example app. Enabled background fetch, background processing. 
Declared that works fine on foreground but does not work. 
Is there anything except from it?

**Comment by Dev-hwang** [comment]
Does the example work fine in debug mode?

**Comment by alperenbaskaya58** [comment]
It works same as debug mode. I need to ask it, if we leave app and use another apps is not  it expected to run along? 
It works like count 5ish and stops the work on example app debug mode.

**Comment by Dev-hwang** [comment]
no. using another app means that the app running the task has entered the background state. 

check this plugin [limitations](https://github.com/Dev-hwang/flutter_foreground_task?tab=readme-ov-file#baby_chick-ios).

if the app can't perform tasks at the exact time, but you want to run it periodically in the background, trythis [flutter_background_service](https://pub.dev/packages/flutter_background_service).

**Comment by alperenbaskaya58** [comment]
Okay, thanks for infroming me about these states.
I know background service interval can not be less than 15 minutes. Is scheduling local notifications then make operations under the notifs working to decrease fetching interval like 30 seconds or is there any limitations again? Or does rooting the phone work?

**Comment by Dev-hwang** [comment]
This plugin does not implement `BGProcessingTaskRequest`. I simply used `Timer.scheduledTimer` to allow short interval while the app is in use. This method has the advantage of being able to communicate with the main isolate (UI isolate) while maintaining the internal state of the TaskHandler.

**Comment by Dev-hwang** [comment]
This plugin does not implement `BGTaskScheduler`. I simply used `Timer.scheduledTimer` to allow short interval while the app is in use. This method has the advantage of being able to communicate with the main isolate (UI isolate) while maintaining the internal state of the TaskHandler.

https://github.com/Dev-hwang/flutter_foreground_task/blob/a61fbcbf6208239fc698ef0f9427fa036719e6e6/ios/Classes/service/BackgroundService.swift#L305C20-L305C40

**Comment by Dev-hwang** [comment]
@alperenbaskaya58 

This plugin does not implement `BGTaskScheduler`. I simply used `Timer.scheduledTimer` to allow short interval while the app is in use. `Timer.scheduledTimer` only runs in the background for about 30 seconds. This is a limitation of iOS. You must return to the app to continue working.

https://github.com/Dev-hwang/flutter_foreground_task/blob/a61fbcbf6208239fc698ef0f9427fa036719e6e6/ios/Classes/service/BackgroundService.swift#L305
