### ISSUE TITLE
Issue when use func  FlutterForegroundTask.sendDataToTask(data)

### ISSUE THREAD

**Issue by buihongvinh** [Dev-hwang/flutter_foreground_task#258]
I call in HomePage

    final Map<String, dynamic> data = {
      "stopCamera" : "true",
    };
    FlutterForegroundTask.sendDataToTask(data);
    
![image](https://github.com/user-attachments/assets/9d0ebe3d-a966-4054-8dd5-8fb6b5475c65)

    But i received Map<Object?, Object?> in Task (onReceiveData).
     so that if I check 
     if(data is Map<String, dynamic>) -> it will return false
    
![image](https://github.com/user-attachments/assets/40923182-eddd-4dc4-a752-c05cd1756a1b)

**Comment by Dev-hwang** [comment]
fixed issue `flutter_foreground_task: 8.3.1`
