### ISSUE TITLE
Flutter stops when closing app from recent apps

### ISSUE THREAD

**Issue by DH-555** [Dev-hwang/flutter_foreground_task#264]
When I close the app from recent apps after the service is running and the notification is showing, the app stops.

For example, the demo prints in the console a thing every X seconds. If the app is closed from recent apps, it's not being printed anymore.

**Comment by Dev-hwang** [comment]
Is the notification content updated even if you close the app in recent apps?

If so, the foreground service has not stopped.

In the example, the count console log is printed in the Widget.

When the app is terminated, the widget is disposed, so the count console log is no longer printed.

Try printing the console log in TaskHandler onRepeatEvent.

```dart
  // Called every [ForegroundTaskOptions.interval] milliseconds.
  @override
  void onRepeatEvent(DateTime timestamp) {
    FlutterForegroundTask.updateService(notificationText: 'count: $_count');

    // Send data to main isolate.
    FlutterForegroundTask.sendDataToMain(_count);

    _count++;
    
    print('count: $_count');
  }
```

**Comment by Dev-hwang** [comment]
The code to be processed in the background must be written in TaskHandler.

**Comment by TheValkDokk** [comment]
Are you testing this on the physical device or emulate ?
Which platform ?
If it's Xiaomi then it will kill the foreground when user remove the app from the recent apps screen

**Comment by Dev-hwang** [comment]
@TheValkDokk 

yes... it seems that it is impossible to prevent the foreground service from being terminated on Xiaomi devices.

many developers have reported that this issue also exists when implementing native apps.

For Xiaomi devices, [DontKillMyApp](https://play.google.com/store/apps/details?id=com.urbandroid.dontkillmyapp&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) might be helpful...

**Comment by fuadarradhi** [comment]
where do you print console, in taskhandler or in main ui?
----
I am using xiaomi for development now, and have not found any problems

**Comment by DH-555** [comment]
> where do you print console, in taskhandler or in main ui?
> 

How to print it in task handler?
From what I understand I'm printing it on task handler

**Comment by DH-555** [comment]
> Are you testing this on the physical device or emulate ?
> Which platform ?
> If it's Xiaomi then it will kill the foreground when user remove the app from the recent apps screen

Emulator

**Comment by Dev-hwang** [comment]
@DH-555 

In the example, the count console log is printed in the Widget State.

```dart
class _ExamplePageState extends State<ExamplePage> {
  void _onReceiveTaskData(Object data) {
    if (data is int) {
      // here
      print('count: $data');
    }
  }
}
```

As you know, widgets are disposed when the app terminates. and the communication port of this plugin is destroyed.

If the communication port is destroyed, data cannot be passed between Main Isolate(UI) and TaskHandler.

Therefore, the `FlutterForegroundTask.sendDataToMain` function does not work.

Try print(count) in the onRepeatEvent callback.

```dart
@override
void onRepeatEvent(DateTime timestamp) {
  FlutterForegroundTask.updateService(notificationText: 'count: $_count');
  
  // here
  print('count: $_count');
}
```

**Comment by DH-555** [comment]
I do it there. Also I'm running there geolocator, and it seems to stop too getting the location. 
Maybe it's something specific to geolocator and not to this package. No idea 🤔

**Comment by Dev-hwang** [comment]
@DH-555 

hmm.. have you tested it with a real device?

i don't know if it will help you, here an example of implementing a background service using the `fl_location` plugin.

**Comment by Dev-hwang** [comment]
@DH-555 

If you want to use the `Geolocator` plugin..

**Don't** call `Geolocator.getCurrentPosition` repeatedly in the `onRepeatEvent` callback.

Instead, subscribe to `Geolocator.getPositionStream` in the `onStart` callback.

**Comment by fuadarradhi** [comment]
> I do it there. Also I'm running there geolocator, and it seems to stop too getting the location. Maybe it's something specific to geolocator and not to this package. No idea 🤔

why you use geolocator if owner of this packgage also have location stream service packgage :)

btw, [fl_location](https://github.com/Dev-hwang/flutter_location) very stable with, plus [flutter_activity_recognition](https://github.com/Dev-hwang/flutter_activity_recognition) also

**Comment by DH-555** [comment]
I tested the plugin provided by him and It works, however geolocator is being destroyed, so the solution is basically using the provided geolocation plugin.

The only problem is that I'm unable now with the stream opened to perform periodic location updates instead of constantly.
Also the printing is not working like previously

**Comment by Dev-hwang** [comment]
@DH-555 

Are you testing on iOS?

Check [readme](https://github.com/Dev-hwang/flutter_foreground_task/blob/master/README.md#baby_chick-ios)

### :baby_chick: iOS

We can also launch `flutter_foreground_task` on the iOS platform. However, it has the following limitations.

* Works only on iOS 12.0 or later.
* **If you force close an app in recent apps, the task will be destroyed immediately.** (this)
* The task cannot be started automatically on boot like Android OS.
* The task will run in the background for approximately 30 seconds due to background processing limitations. but it works fine in the foreground.

This plugin does not implement `BGTaskScheduler`. I simply used `Timer.scheduledTimer` to allow short interval while the app is in use. `Timer.scheduledTimer` only runs in the background for about 30 seconds. This is a limitation of iOS. You must return to the app to continue working.

https://github.com/Dev-hwang/flutter_foreground_task/blob/a61fbcbf6208239fc698ef0f9427fa036719e6e6/ios/Classes/service/BackgroundService.swift#L305

**Comment by DH-555** [comment]
@Dev-hwang Nope, I'm testing in Android. I managed to solve the issue by restarting the app after establishing the interval in your location plugin. 

Huge thanks for everything!

**Comment by DH-555** [comment]
Hello! Update on this: I'm using the example you provided to send the location from the user to an appwrite server. The Issue is that it stops sending it while the app is closed, so I receive updates only with the app opened
