### ISSUE TITLE
Unable to toggle `allow permission` for foreground service

### ISSUE THREAD

**Issue by reduxdj** [Dev-hwang/flutter_foreground_task#266]
The settings menu is shown, however I am unable to turn on the "Alarms and Reminders" feature.

**Comment by Dev-hwang** [comment]
Did you add "android.permission.SCHEDULE_EXACT_ALARM" permission?

```manifest
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
```

If the problem still occurs, please tell me the device model and OS version.

If the user manually disables the permission, your app will no longer be able to request the permission.
settings location: **Settings > Apps > Menu > Special Access > Alarms and Reminders**
