### ISSUE TITLE
I think onRepeatEvent() is not being called properly.

### ISSUE THREAD

**Issue by cho-4** [Dev-hwang/flutter_foreground_task#267]
foregroundTaskOptions: ForegroundTaskOptions(
        eventAction: ForegroundTaskEventAction.repeat(300000),
        autoRunOnBoot: true,
        autoRunOnMyPackageReplaced: true,
        allowWakeLock: false,
        allowWifiLock: false,
      ), 
I wrote it as above and onRepeatEvent() is written below, but saveSleepBackupData() is not called.
void onRepeatEvent(DateTime timestamp) async {
    await sleepDataBloc.saveSleepBackupData(299);
  } 

I use the latest version 8.6.0 and I'm developing using an  android real device.

**Comment by fuadarradhi** [comment]
what version ?
i think  eventAction is not exists in latest version.

```
foregroundTaskOptions: const ForegroundTaskOptions(
        interval: 300000,
        isOnceEvent: false,
        autoRunOnBoot: true,
        autoRunOnMyPackageReplaced: true,
        allowWakeLock: false,
        allowWifiLock: false,
      ),
```

**Comment by cho-4** [comment]
I use the latest version 8.6.0

**Comment by Dev-hwang** [comment]
please tell me the OS version of the device you tested.

and, check if the same problem occurs even if set the allowWakeLock option to true.

if the device enters doze mode, the onRepeatEvent callback is likely to be delayed.

reduce delay, request to ignore battery optimization.

```dart
// Android 12+, there are restrictions on starting a foreground service.
//
// To restart the service on device reboot or unexpected problem, you need to allow below permission.
if (!await FlutterForegroundTask.isIgnoringBatteryOptimizations) {
  // This function requires `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission.
  await FlutterForegroundTask.requestIgnoreBatteryOptimization();
}
```

**Comment by cho-4** [comment]
> please tell me the OS version of the device you tested.
> 
> and, check if the same problem occurs even if set the allowWakeLock option to true.
> 
> if the device enters doze mode, the onRepeatEvent callback is likely to be delayed.
> 
> reduce delay, request to ignore battery optimization.
> 
> ```dart
> // Android 12+, there are restrictions on starting a foreground service.
> //
> // To restart the service on device reboot or unexpected problem, you need to allow below permission.
> if (!await FlutterForegroundTask.isIgnoringBatteryOptimizations) {
>   // This function requires `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission.
>   await FlutterForegroundTask.requestIgnoreBatteryOptimization();
> }
> ```

**Comment by cho-4** [comment]
The OS version I use is Android 14, and I have already set the battery limit option.

**Comment by Dev-hwang** [comment]
@cho-4 

You need to check whether the saveSleepBackupData function is not working or the onRepeatEvent callback is not firing.

Please check whether the notification text is updated in the onRepeatEvent callback.

```dart
  int _count = 0;

  @override
  void onRepeatEvent(DateTime timestamp) {
    // update notificationText
    FlutterForegroundTask.updateService(
      notificationText: 'count: $_count',
    );

    // your function
    try {
      sleepDataBloc.saveSleepBackupData(299);
    } catch (error) {
      print('error: $error');
    }

    _count++;
  }
```

**Comment by Dev-hwang** [comment]
Please provide a sample project so i will check the problem.

**Comment by cho-4** [comment]
As you said, I changed the allowWakeLock option to true and it seems to work properly. Thanks for the reply

**Comment by cho-4** [comment]
And is there a way to make onRepeatEvent() work not immediately after it changes to the background, but after the time set in repeat() after it changes to the background? It's a bit different from my intention to run it once as soon as it changes to the background.

**Comment by Dev-hwang** [comment]
@cho-4 

> And is there a way to make onRepeatEvent() work not immediately after it changes to the background, but after the time set in repeat() after it changes to the background? It's a bit different from my intention to run it once as soon as it changes to the background.

ok. i have confirmed the issue on Android platform. I will tell you after fixing the issue.

**Comment by Dev-hwang** [comment]
@cho-4 

check latest version

**Comment by cho-4** [comment]
@Dev-hwang 
thank you so much! And would you mind if I ask another question?

I use the code below in main.dart, but is it possible to use a singleton object in taskhandler? This is because an error occurred saying that the variable was not initialized even though it was clearly already a saved variable.

class MyTaskHandler extends TaskHandler {
  SleepDataBloc sleepDataBloc = SleepDataBloc();

  @override
  void onStart(DateTime timestamp) {
    print("저장 반복 시작");
  }

  @override
  void onRepeatEvent(DateTime timestamp) {
    sleepDataBloc.saveSleepBackupData(100);
  }

  @override
  void onDestroy(DateTime timestamp) {
    print('foreground service end');
  }
  void onNotificationPressed() {
    FlutterForegroundTask.launchApp('/');
    print('onNotificationPressed');
  }
}

**Comment by Dev-hwang** [comment]
@cho-4 

No. The singleton instance created in TaskHandler and the singleton instance created in the Main app are different.

- Main app runs in a space called `Main(UI) Isolate`.
- TaskHandler runs in a space called `Background Isolate`.

> All Dart code runs in [isolates](https://dart.dev/language/concurrency), which are similar to threads, but differ in that isolates have their own isolated memory. They do not share state in any way, and can only communicate by messaging. By default, Flutter apps do all of their work on a single isolate – the main isolate.

**Comment by cho-4** [comment]
@Dev-hwang 
Ah, I see, thanks for the reply. I'll look for another way.
