### ISSUE TITLE
Android 14 Crash (pedometer and flutter_foreground_task)

### ISSUE THREAD

**Issue by Aashish-Dahal** [Dev-hwang/flutter_foreground_task#269]
`java.lang.RuntimeException: Unable to start service com.pravera.flutter_foreground_task.service.ForegroundService@f0e7dfb with Intent { cmp=jp.yonagoshi.frailty/com.pravera.flutter_foreground_task.service.ForegroundService }: java.lang.SecurityException: Starting FGS with type health callerApp=ProcessRecord{152f19e 4320:jp.yonagoshi.frailty/u0a195} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
E/AndroidRuntime( 4320): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)
E/AndroidRuntime( 4320): 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/AndroidRuntime( 4320): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
E/AndroidRuntime( 4320): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4320): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 4320): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 4320): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 4320): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 4320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime( 4320): Caused by: java.lang.SecurityException: Starting FGS with type health callerApp=ProcessRecord{152f19e 4320:jp.yonagoshi.frailty/u0a195} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_HEALTH] any of the permissions allOf=false [android.permission.ACTIVITY_RECOGNITION, android.permission.BODY_SENSORS, android.permission.HIGH_SAMPLING_RATE_SENSORS] 
E/AndroidRuntime( 4320): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/AndroidRuntime( 4320): 	at android.os.Parcel.createException(Parcel.java:3041)
`

Permissions:
`    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="FOREGROUND_SERVICE_HEALTH"/>
    <uses-permission android:name="HIGH_SAMPLING_RATE_SENSORS"/>
    <uses-permission android:name="android.permission.BODY_SENSORS"/>
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

Service: 
`   <service 
         android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
         android:foregroundServiceType="health" 
         android:stopWithTask="true"
         android:exported="false" />`

flutter_foreground_task: ^7.0.0

**Comment by Bivek10** [comment]
I have facing same issue

**Comment by Dev-hwang** [comment]
서비스를 시작하기 전에 권한이 허용되어야 합니다.

**Comment by Dev-hwang** [comment]
@Aashish-Dahal @Bivek10 

The permissions[`android.permission.ACTIVITY_RECOGNITION`, `android.permission.BODY_SENSORS`] must be granted before starting the service.

The `pedometer` plugin doesn't seem to have a function that requests the BODY_SENSORS permission.

You can request permissions using [permission_handler](https://pub.dev/packages/permission_handler).

```dart
  Future<void> _requestPermissions() async {
    const Permission activityPermission = Permission.activityRecognition;
    if (!(await activityPermission.isGranted)) {
      await activityPermission.request();
    }

    const Permission sensorsPermission = Permission.sensors;
    if (!(await sensorsPermission.isGranted)) {
      await sensorsPermission.request();
    }
  }
```
