### ISSUE TITLE
Problem with background on iOS

### ISSUE THREAD

**Issue by nicop2000** [Dev-hwang/flutter_foreground_task#27]
Hi, I use the GeoLocator's position stream and send the updates to the foreground task receiveport which I listen to. On Android it works fine but on iOS it stops after about 10-15 seconds after returning to the home screen. Any ideas how to fix this?
```
Geolocator.getPositionStream(intervalDuration: Duration(seconds: 1)).listen((event) {
      print(event);
      sendPort!.send(event);
    });
```
```
_receivePort = receivePort;
      _receivePort!.listen((message) {
        print("RECIEVE PORT");
        print(message);
      });
```

Thanks anyway :)

**Comment by Dev-hwang** [comment]
@nicop2000

As explained by README, the iOS platform has limitations on background processing.Therefore, the task stops after 15-30 seconds in the background. 

At my current level, there is no way to solve it. If there is a way to solve the problem, please provide a PR, I would appreciate it.

**Comment by Dhirajraje** [comment]
Did you find solution for IOS foreground.
