### ISSUE TITLE
Error turn off screen when app is active Android 14

### ISSUE THREAD

**Issue by tuyen3962** [Dev-hwang/flutter_foreground_task#273]
library version:

Flutter 3.22.3
flutter_foreground_task: ^8.8.0

Description issue:
When I move the application to the background, it work fine. But when the application is active in the screen, I turn off my device and it throw error

java.lang.RuntimeException: Unable to start service com.pravera.flutter_foreground_task.service.ForegroundService@3cbbdfd with Intent { cmp=com.vnconnections.app/com.pravera.flutter_foreground_task.service.ForegroundService }: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{f3168 30672:com.vnconnections.app/u0a496} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission

Caused by: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{f3168 30672:com.vnconnections.app/u0a496} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission

Please support me in this case, I also setup the manifest as you mention in other issue and the document but it doesn't work for me. Please revise my manifest

<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET"/>
      
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />

    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:label="asdas"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

             
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <service
            android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
            android:foregroundServiceType="location"
            android:stopWithTask="true"
            android:exported="false" />

        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="@string/GOOGLE_MAPS_API_KEY"/>
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

**Comment by tuyen3962** [comment]
I also add these following permission in Manifest file. But it does not work. It only occur in the case of turning off the screen when the application is active

**Comment by tuyen3962** [comment]
With the case of integrating the isar and timer in the foreground task, do i need to add the permission in the manifest?

**Comment by Dev-hwang** [comment]
i have no experience with isar. can you provide sample project?

**Comment by tuyen3962** [comment]
Oke wait me a minutes. But I test with the always location permission and it work for me when turn off the screen. With the case of whileInUse it dont' work.
However, I test in other with just WhileInUse permission and it work in the case of turning off screen when app is active in the screen and put the application into background mode.

**Comment by Dev-hwang** [comment]
You must always allow the Location permission to get your location in the background.

![image](https://github.com/user-attachments/assets/11d61c7d-601d-4a08-8b1b-5dc1e6db5244)

**Comment by tuyen3962** [comment]
But in the other application, it work with the while in use location permission when it run in the background

**Comment by Dev-hwang** [comment]
ok. sample project is ready, I check this issue.

**Comment by tuyen3962** [comment]
So do I need give you the sample project to test this case?

**Comment by Dev-hwang** [comment]
I tested in whileInUse state but the above error did not occur 😢

**Comment by tuyen3962** [comment]
Oke, you can try to run in during the amount of time like 30m to whether it run properly

**Comment by tuyen3962** [comment]
https://github.com/tuyen3962/location_example.git

I have created the example basing on my app. You can check it. But in this example, it don't work with the case of while in use location. But I face another issue that I crash when call this function openIgnoreBatteryOptimizationSettings

**Comment by Dev-hwang** [comment]
@tuyen3962 

I found it. This is related to limitations on Android platform.

The android [official documentation](https://developer.android.com/develop/background-work/services/foreground-services#wiu-restrictions) explains it as follows:

> For while-in-use permissions, this causes a potential problem. If your app has a while-in-use permission, it only has that permission while it's in the foreground. This means if your app is in the background, and it tries to create a foreground service of type camera, location, or microphone, the system sees that your app doesn't currently have the required permissions, and it throws a SecurityException.

You are trying to start the location service when `AppLifecycleState.hidden`:

```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!hasStart && state == AppLifecycleState.hidden) {
      hasStart = true;
      LocationBackgroundSetup.startService(); // here
    } else if (hasStart && state == AppLifecycleState.resumed) {
      hasStart = false;
      LocationBackgroundSetup.stopService();
    }
    super.didChangeAppLifecycleState(state);
  }
```

The moment you turn off the screen, `AppLifecycleState.hidden` will be triggered and the app will enter the background state.

At this time, if you try to start location service in the while-in-use state, a SecurityException will be thrown.

This is a platform limitation, so you should always allow location permission 😢

**Comment by tuyen3962** [comment]
ak this demo I start the service when the state of app is hidden. But in my personal project, I check it when the application is inactive and it work. Is there any trick? :)))

**Comment by Dev-hwang** [comment]
In my case, SecurityException occurs even in AppLifecycleState.active state.

I think you should always allow permission to safely start the service.

**Comment by tuyen3962** [comment]
Huh, maybe that. Thank you for your support
