### ISSUE TITLE
FlutterForegroundTask.openIgnoreBatteryOptimizationSettings() crash app

### ISSUE THREAD

**Issue by tuyen3962** [Dev-hwang/flutter_foreground_task#275]
When I call this function to open the setting in order to ignore the optimization battery, it crash.

**Comment by Dev-hwang** [comment]
Thank you for reporting the issue. I will publish after fixing the issue.

**Comment by Dev-hwang** [comment]
@tuyen3962 

This issue has been resolved. please update latest version.

**Comment by tuyen3962** [comment]
Oke thank you so much
