### ISSUE TITLE
Missing foreground service type

### ISSUE THREAD

**Issue by deakjahn** [Dev-hwang/flutter_foreground_task#281]
When publishing a new upgrade to the Play Store that contains the new 8.10.0 version, the store refuses to accept it with the following warning:

```
Missing foreground service type

From Android 14, developers must specify service types when foreground services are found in their app's manifest. Missing foreground service types may cause your app to crash. Your app's manifest declares com.pravera.flutter_foreground_task.service.ForegroundService, which starts in the foreground in the following place:

com.pravera.flutter_foreground_task.service.ForegroundService.com.pravera.flutter_foreground_task.service.ForegroundService.u

Make sure service types for the services that start in the foreground are specified in your app's manifest.
```

The [docs](https://developer.android.com/about/versions/14/changes/fgs-types-required) seem to suggest that this is something we have to provide, so it would probably be nice to add to your documentation.

**Comment by deakjahn** [comment]
On second thought, it might not be just a documentation issue. [Foreground service types](https://developer.android.com/develop/background-work/services/fg-service-types) states that, depending on the actual service type, you need to pass different constants to `startForeground()`. So, you probably have to introduce an enum to be passed during initialization.

**Comment by Dev-hwang** [comment]
@deakjahn 

It has already been added to the document. However, I will add that if the developer does not specify this, the app cannot be released to the Play Store.

Thanks for your suggestion.

**Comment by deakjahn** [comment]
Yes, you're right, the service type itself is in the example. You might also want to link to that documentation page because granting the indvidual types is also linked to other specific permissions that people need to be aware of.
