### ISSUE TITLE
com.pravera.flutter_foreground_task.service.RebootReceiver Exception

### ISSUE THREAD

**Issue by jaypokar** [Dev-hwang/flutter_foreground_task#283]
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.pravera.flutter_foreground_task.service.RebootReceiver: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{partner.dropon.delivery/com.pravera.flutter_foreground_task.service.a}

**Comment by jaypokar** [comment]
I am not using the service at all, not even starting the service from this.
I am using this only to check that my app is in foreground or to launch the app when it's in background that's it.

**Comment by Dev-hwang** [comment]
@jaypokar 

I think this plugin does not suit your purpose.

You will need to add the service tag in manifest for this plugin to work properly.

**Comment by jaypokar** [comment]
actually I have updated this to latest version but it was working well before in flutter_foreground_task: ^6.5.0, which I have been using.

**Comment by Dev-hwang** [comment]
@jaypokar 

you're right. In the new version, i check whether to restart the service by looking at the status of the service tag.

https://github.com/Dev-hwang/flutter_foreground_task/blob/dc012e5b1b0263f263b969af154d2d39b5264443/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/RebootReceiver.kt#L23

An exception occurs if the component name cannot be found here.

https://github.com/Dev-hwang/flutter_foreground_task/blob/dc012e5b1b0263f263b969af154d2d39b5264443/android/src/main/kotlin/com/pravera/flutter_foreground_task/utils/ForegroundServiceUtils.kt#L13

However, the lower the possibility of exceptions occurring, the better, so this part will be handled as an exception in the next version.

**Comment by Dev-hwang** [comment]
You can fork this project and use it until a new version is published.

db2abe4a569b818978fabcfb25902101d0053050

**Comment by Dev-hwang** [comment]
@jaypokar 

Version 8.10.4 has been published.

Please check and let me know if there are any problems.
