### ISSUE TITLE
Should notifications be mandatory?

### ISSUE THREAD

**Issue by cho-4** [Dev-hwang/flutter_foreground_task#285]
I don't want to use notifications, is there any way?

**Comment by Dev-hwang** [comment]
@cho-4 

On Android 13 (API level 33) or higher, if the user denies the [notification permission](https://developer.android.com/guide/topics/ui/notifiers/notification-permission), they still see notices related to foreground services in the [Task Manager](https://developer.android.com/guide/components/foreground-services#handle-user-initiated-stop) but don't see them in the notification drawer.

The notefication will always appear in older versions.

Foreground services can run for a long time compared to other background api. This uses a lot of battery and memory resources on the device, so it would be correct to notify the user through a notification. Please be considerate of users and provide transparency in service use.

**Comment by cho-4** [comment]
@Dev-hwang 

Thank you for your reply. 

So what you’re saying is that there’s no way to just turn off notifications, right?

**Comment by Dev-hwang** [comment]
@cho-4 

Yes.. I'm sorry I couldn't help you :cry:

**Comment by cho-4** [comment]
@Dev-hwang 

No, thank you for your reply.
