### ISSUE TITLE
android:foregroundServiceType="microphone"

### ISSUE THREAD

**Issue by mening12001** [Dev-hwang/flutter_foreground_task#291]
There is an issue when setting the type of the service to "microphone" on Android 14. The android.permission.FOREGROUND_SERVICE_MICROPHONE must be acquired. 

Please consider solving this issue by including the permission request. Thank you!

**Comment by Dev-hwang** [comment]
Hello, @mening12001 

To start the foreground service on android14, `foregroundServiceType` and `permission` are required.

https://developer.android.com/about/versions/14/changes/fgs-types-required#microphone

<img width="500" alt="image" src="https://github.com/user-attachments/assets/01d93d93-46b6-473b-8708-579129e9f91d">

Therefore, it must be declared as follows in the Manifest:

```
<!-- required -->
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

<!-- foregroundServiceType: microphone -->
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MICROPHONE" />

<!-- Warning: Do not change service name. -->
<service 
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="microphone"
    android:exported="false" />
```

**Comment by mening12001** [comment]
Hello, Thank you for the response.

**Comment by mening12001** [comment]
Hello, Thank you for the response.
