### ISSUE TITLE
Delay in starting the foreground task

### ISSUE THREAD

**Issue by akshaykap11** [Dev-hwang/flutter_foreground_task#292]
There is delay of 3 seconds before the foreground service actually starts. Is there a way to start the service immediately passing this parameter somewhere -> NotificationCompat.FOREGROUND_SERVICE_IMMEDIATE

**Comment by akshaykap11** [comment]
no, it does not occur in the basic example.

**Comment by Dev-hwang** [comment]
@akshaykap11 

Could you provide steps to reproduce the issue or share a sample project?

**Comment by Dev-hwang** [comment]
I will close the issue as there is no response.
