### ISSUE TITLE
The base sample project is invalid after the background

### ISSUE THREAD

**Issue by willbetheone** [Dev-hwang/flutter_foreground_task#294]
Hello,
In the base sample project, after about five counter increments in the background of the application, the subsequent notification bar will not be incremented and there will be no print

**Comment by willbetheone** [comment]
The permission isIgnoringBatteryOptimizations  is true, but the app still doesn't work in the background。

**Comment by Dev-hwang** [comment]
Hello, @willbetheone 

Did you add the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission in the manifest?

```xml
<manifest>
    <!-- Add permissions -->
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
</manifest>
```

If the battery optimization ignore request prompt does not appear, you can try directly request as follows:

```dart
Future<void> _requestPermissions() async {
   // This function requires `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission.
   await FlutterForegroundTask.requestIgnoreBatteryOptimization();
}
```

**Comment by Dev-hwang** [comment]
There may be restrictions on background services depending on the device manufacturer. Please let me know the devices you tested.

And please check if it works correctly in the simulation as well.

**Comment by willbetheone** [comment]
Hello, @Dev-hwang 

It's a pleasure to receive your message. I did the test demo on OnePlus 9R.

**Comment by willbetheone** [comment]
Hello , @Dev-hwang
I just tried it on the simulator and it worked fine.
Thanks for the reply.

Next steps 
For the OnePlus 9R mobile phone, additional permissions are required. How can we handle it better? Do you have any good suggestions?

-- Zander

**Comment by Dev-hwang** [comment]
@willbetheone 

This issue seems to be related to the manufacturer of OnePlus devices.

I couldn't find a way to programmatically go to the specific settings(power consumption controls) page. It seems to be a settings page for OnePlus devices.

so, it seems necessary to provide a guide for OnePlus users to go to the settings page and enable background.

I'm sorry that I couldn't be more helpful 😢
