### ISSUE TITLE
Android 14 not open

### ISSUE THREAD

**Issue by srinathvgts** [Dev-hwang/flutter_foreground_task#299]
e: file:///Users/srinathvishgyana/.pub-cache/hosted/pub.dev/flutter_foreground_task-8.14.0/android/src/main/kotlin/com/pravera/flutter_foreground_task/MethodCallHandlerImpl.kt:23:5 Unresolved reference: FlutterForegroundTaskPluginChannel
e: file:///Users/srinathvishgyana/.pub-cache/hosted/pub.dev/flutter_foreground_task-8.14.0/android/src/main/kotlin/com/pravera/flutter_foreground_task/MethodCallHandlerImpl.kt:171:5 'init' overrides nothing
e: file:///Users/srinathvishgyana/.pub-cache/hosted/pub.dev/flutter_foreground_task-8.14.0/android/src/main/kotlin/com/pravera/flutter_foreground_task/MethodCallHandlerImpl.kt:176:5 'setActivity' overrides nothing
e: file:///Users/srinathvishgyana/.pub-cache/hosted/pub.dev/flutter_foreground_task-8.14.0/android/src/main/kotlin/com/pravera/flutter_foreground_task/MethodCallHandlerImpl.kt:180:5 'dispose' overrides nothing

**Comment by Dev-hwang** [comment]
@srinathvgts

This issue seems to be related to the local build cache.

try command

```
flutter clean
flutter pub get
flutter run
```

**Comment by timsar2** [comment]
from android 14 it need to pass service type when going to startService,
service type like:
healt
data_sync
...

**Comment by Dev-hwang** [comment]
This issue is a known problem, and I believe it has been resolved through a build clean.

I will close this issue.
