### ISSUE TITLE
Foreground service stops on killing the application

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#3]

**Comment by Dev-hwang** [comment]
Foreground task of this plugin is implemented in the Flutter framework. So when the FlutterActivity ends, the foreground task is killed. The reason for this implementation is that the code that works in the Flutter framework cannot be transferred or executed to a specific platform.

This plugin only works when the app is running in the background (when the home button or back button is pressed).
If you want the foreground service to run even when the app process is killed, you need to write the desired behavior in Android native code and implement the foreground service.

**Comment by darshansatra1** [comment]
I tried this [flutter_foreground_service_plugin](https://pub.dev/packages/flutter_foreground_service_plugin) plugin and it luckily worked. It would be great if you can implement this behaviour in your plugin. Your plugin is built very nicely and thanks for building it, although this is the limitation for me that I can not ignore.

**Comment by Dev-hwang** [comment]
Thank you. I checked the plugin. It seems to be possible to implement using `PluginUtilities`. Let's test and implement `PluginUtilities`.

**Comment by darshansatra1** [comment]
Any updates? @Dev-hwang

**Comment by Dev-hwang** [comment]
> Any updates? @Dev-hwang

I'm busy working on other projects. Will update in the near future.

**Comment by Dev-hwang** [comment]
@darshansatra1 The plugin has been updated. There are many changes, so please refer to the readme.

**Comment by TheLastGimbus** [comment]
Hi there! How did you fix this? For me, service still closes when I swipe the app out from "recents" :confused: I have pure stock android... I tried adding `WithForegroundTask` (no idea how it works but okay), didn't help :(

**Comment by Dev-hwang** [comment]
@TheLastGimbus 
Try removing the stopWithTask setting in the service tag.

<service android:name="com.pravera.flutter_foreground_task.service.ForegroundService" />

**Comment by TheLastGimbus** [comment]
Jeez this was so obvious, thanks!!

Um by the way, it looks like hot-reload/even restart doesn't work for it at all D: I need to re-install the whole app for it to work :( Is this normal? Honestly it's okay if it's required - in exchange for **working** plugin :sparkling_heart: there are so many of them and none work :confounded: 

Oh and if may I ask one more question - I wanted to have my code work in more like "lifecycle" way - set things up *before* `FlutterForegroundTask.initDispatcher`, and then close them in `onDestroy`, like this:

```dart
void globalMethod() async {
  StreamSubscription stream =
      Stream.periodic((const Duration(seconds: 1))).listen((event) async {
    print("Stream :DD");
    await FlutterForegroundTask.update(
      notificationTitle: "Doing something...",
      notificationText: event.toString(),
    );
  });
  FlutterForegroundTask.initDispatcher(
    (timestamp) async {
      // Nothing in here
    },
    onDestroy: (timestamp) async {
      await stream.cancel();
      print('onDestroy D:');
    },
  );
}
```
Everything should work, right? It does now when I try it, tho I wanted to ask because maybe you have some bad experiences or smth :P

**Comment by Dev-hwang** [comment]
@TheLastGimbus 
Data and event handling must only be done inside the `FlutterForegroundTask.initDispatcher` function.
If you don't know exactly what you want, but want to subscribe to the stream, try this method.

```dart
void callback() {
  final positionStream = Geolocator.getPositionStream();
  StreamSubscription<Position>? streamSubscription;

  FlutterForegroundTask.initDispatcher((timestamp) async {
    if (streamSubscription != null) return;

    streamSubscription = positionStream.listen((event) {
      print('timestamp: ${timestamp.toString()}');

      FlutterForegroundTask.update(
          notificationTitle: 'Current GPS localization',
          notificationText: '${event.latitude}, ${event.longitude}');
    });
  }, onDestroy: (timestamp) async {
    await streamSubscription?.cancel();
    print('callback() is dead.. x_x');
  });
}
```

**Comment by TheLastGimbus** [comment]
Thanks! I'll do it like this

About hot-reload: I tried `Isolate.current.kill()` at the and of `onDestroy` - didn't work :disappointed: if you had any idea, I would be very grateful (and had nice couple of hours wasted on re-installing it less :P )

Nevertheless - thanks very much for this plugin! Something finally works!
