### ISSUE TITLE
save BluetoothConnection variable in foreground

### ISSUE THREAD

**Issue by alishe79** [Dev-hwang/flutter_foreground_task#30]
Hi. 
Thank you for develop this plugin.
This dependency solves all my problems except for two, which I will explain below:

1. how save BluetoothConnection class variable  . 
    now BluetoothConnection variable is dead when app close from task manager.
    I'm only test this on Android Devices.
    
2. I'm not able to network call in background i test two dependeny. [retrofit](https://pub.dev/packages/retrofit) & [http](https://pub.dev/packages/http)
    
I am also in an urgent position that encourages me to do this today.
Thanks in advance for taking the time to respond to this issue

**Comment by alishe79** [comment]
I found the main problem.
The main problem is that receivePort crashes  after closing the application from task Manager. 
What is the reason for this? 
How do I fix this problem?

**Comment by Dev-hwang** [comment]
It's hard to pinpoint exactly what's going on. Could you please provide some sample code or project?

For network issues, try setting `allowWifiLock` to `true` as on this [page](https://github.com/Dev-hwang/flutter_foreground_task/issues/28).

**Comment by Dev-hwang** [comment]
[This project](https://github.com/Dev-hwang/ble_test) is part of a project I've been working on in the past. This is an example of transmitting the information of the nearest device among the discovered Bluetooth devices to the server. There is no permission handler, so manually grant location permission. It works fine on Android 10 (sdk 30).

**Comment by alishe79** [comment]
`/// requires => material.dart & flutter_bluetooth_serial 0.3.2
import 'dart:convert';
import 'dart:typed_data';
import 'package:project/provider/bluetooth/background_task.dart';
import 'package:project/provider/bluetooth/global_live_data.dart';
import 'package:flutter_bluetooth_serial/flutter_bluetooth_serial.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';
import 'package:permission_handler/permission_handler.dart';

// FlutterReactiveBle _flutterReactiveBle = FlutterReactiveBle();



class OBDII {
  /// OBDII Settings commands
  static const String RESET_ALL = "AT Z";

  /// OBDII Car Parameters Commands
  static const String Voltage = "AT RV";
  static const String EngineSpeed = "01 0C";
  static const String CarSpeed = "01 0D";
  static const String WeatherTemp = "01 05";
  static const String FuelRate = "01 0B";


  /****
   *
   *
   *
   */
  /// send this commands before send any command by priority in the list
  /// TODO : ** Important ** -> Add every command in obdConfigCommands to
  /// TODO : ** first of carParamsCommands list in order **
  static List<String> obdConfigCommands = [
    RESET_ALL,
    "AT E 0",
    "AT SP 0",
    "AT AL",
    "AT L1",
    "AT H1",
    "AT SH 81 10 F1"
  ];
  /// For read car parameters
  static List<String> carParamsCommands = [
    RESET_ALL,
    "AT E 0",
    "AT SP 0",
    "AT AL",
    "AT L1",
    "AT H1",
    "AT SH 81 10 F1",
    Voltage, // Voltage
    EngineSpeed, // Engine Speed
    CarSpeed, // Car Speed
    WeatherTemp, // Weather Temp
    FuelRate, // Fuel Rate
  ];


  Future<void> setBaseConfig({Function()? onSuccess, Function()? onError}) async {
    if (connection == null) {
      if (onError != null){
        onError();
      }
      return;
    }

    write(obdConfigCommands[0], 0);
    setOnDataReceived((requestCode, serialResponse){
      if (requestCode < (obdConfigCommands.length - 1)){
        write(obdConfigCommands[requestCode + 1], (requestCode + 1));
      } else {
        if (onSuccess != null){
          onSuccess();
        }
      }
    });
  }

   /*****************************************
   *                                        *
   *        Engine Speed Variables          *
   *                                        *
   ******************************************/

  /// rpm variables
  double engineSpeed = 0;
  double get rpm => engineSpeed;

  /// calculate rpm
  double calculateRPM(String command, String response, {int returnBytes = 2 }){
    List<String> bytes = calculateFrames(command, response, returnBytes: returnBytes);
    if (bytes.length == returnBytes){
      String a = bytes[0];
      String b = bytes[1];

      engineSpeed = (((256 * int.parse(int.parse(a, radix: 16).toRadixString(10))) + int.parse(int.parse(b, radix: 16).toRadixString(10))) / 4);

    }
    return rpm;
  }


  /// calculate speed
  String calculateSpeed(String command, String response, {int returnBytes = 1 }){
    List<String> bytes = calculateFrames(command, response, returnBytes: returnBytes);
    if (bytes.length == returnBytes){
      String a = bytes[0];
      String speed = int.parse(a, radix: 16).toRadixString(10);
      return speed;
    }
    return "0";
  }
  /// calculate temp
  String calculateTemp(String command, String response, {int returnBytes = 1 }){
    List<String> bytes = calculateFrames(command, response, returnBytes: returnBytes);
    if (bytes.length == returnBytes){
      String a = bytes[0];
      String temp = (int.parse((int.parse(a, radix: 16)).toRadixString(10)) - 40).toString();
      return temp;
    }
    return "0";
  }

  List<String> calculateFrames(String command, String response, {int returnBytes = 2 }){
    String cmd = "${(int.parse(command[0]) + 4)}${command.substring(1, command.length)}";
    if (!response.contains(cmd)){
      return [];
    }
    List<String> responseCharacters = response.split(" ");
    List<String> bytes = [];
    bool addToBytes = false ;
    for (int i = 0; i < responseCharacters.length; i++){
      if ((responseCharacters.length - 1) == i){
        if (addToBytes){
          bytes.add(responseCharacters[i]);
        }
      } else {
        if (!addToBytes){
          if (responseCharacters[i] == cmd.split(" ")[0] && responseCharacters[(i+1)] == cmd.split(" ")[1]){
            i = i + 1 ;
            addToBytes = true ;
          }
        } else {
          bytes.add(responseCharacters[i]);
        }
      }

      if (bytes.length == returnBytes){
        break ;
      }

    }

    return bytes ;
  }

  List<String> calculateDtcFrames(String command, String response){
    String cmd = "${(int.parse(command[0]) + 4)}${command[1]}";
    if (!response.contains(cmd)){
      return [];
    }
    List<String> responseCharacters = response.split(" ");
    List<String> bytes = [];
    bool addToBytes = false ;
    for (int i = 0; i < responseCharacters.length; i++){
      if ((responseCharacters.length - 1) == i){
        if (addToBytes){
          bytes.add(responseCharacters[i]);
        }
      } else {
        if (!addToBytes){
          if (cmd.contains(" ")){
            if (responseCharacters[i] == cmd.split(" ")[0] && responseCharacters[(i+1)] == cmd.split(" ")[1]){
              i = i + 1 ;
              addToBytes = true ;
            }
          } else {
            if (responseCharacters[i] == cmd){
              addToBytes = true ;
            }
          }

        } else {
          bytes.add(responseCharacters[i]);
        }
      }
    }

    return bytes ;
  }



  /******************************************
   *                                        *
   *           Car Speed Variables          *
   *                                        *
   ******************************************/

  /// rpm variables
  double fuelRate = 0;
  double get fr => fuelRate;

  /// calculate fuelRate
  double calculateFuelRate(String command, String response, {int returnBytes = 1 }){
    List<String> bytes = calculateFrames(command, response, returnBytes: returnBytes);
    if (bytes.length == returnBytes){
      String a = bytes[0];

      fuelRate = fFuel(
          rpmLiveData[rpmLiveData.length - 1].data,
          double.parse(int.parse(a, radix: 16).toRadixString(10)),
          tempLiveData[tempLiveData.length - 1].data
      );

    }
    return fuelRate;
  }



}

BluetoothState _bluetoothState = BluetoothState.UNKNOWN;
FlutterBluetoothSerial _bluetooth = FlutterBluetoothSerial.instance;
bool searching = true ;

bool isWriting = false ;
int _requestCode = 999999999999999999 ;

Map<String, String> log = Map();

void resetBluetooth(){
  connection = null;
  searching = true;
}

Future<bool> initBluetooth(Function(bool isInitialed) onDone) async {
  bool status = await Permission.location.request().isGranted;
  _bluetoothState = await FlutterBluetoothSerial.instance.state;
  onDone(status);
  return status;
}

bool isBluetoothEnable () {
  if (_bluetoothState == BluetoothState.STATE_OFF) {
    return false ;
  } else if (_bluetoothState == BluetoothState.STATE_ON) {
    return true ;
  } else {
    throw Exception("obdii not initialed");
  }
}


Future<bool> enableBluetooth () async {
  bool status = false;
  if (_bluetoothState == BluetoothState.STATE_OFF) {
    bool? newStatus = await FlutterBluetoothSerial.instance.requestEnable();
    if (newStatus != null && newStatus != false){
      status = true ;
    }
  } else {
    status = true ;
  }
  return status ;
}


Future<bool?> disableBluetooth () async {
  bool? status = false;
  if (_bluetoothState == BluetoothState.STATE_ON) {
    status = await FlutterBluetoothSerial.instance.requestDisable();
  }
  return status ;
}


Future<List<BluetoothDevice>> getPairedDevices () async {
  return await _bluetooth.getBondedDevices();
}

Future<List<BluetoothDevice>> getNearbyDevices () async {
  List<BluetoothDevice> discoveryDevices = [];
  return await _bluetooth.startDiscovery().listen((event) {
    final existingIndex = discoveryDevices.indexWhere((element) => element.address == event.device.address);
    if (existingIndex >= 0) {
      discoveryDevices[existingIndex] = event.device;
    } else {
      if (event.device.name != null){
        discoveryDevices.add(event.device);
      }
    }
  }).asFuture(discoveryDevices);
}

Future<void> connect(BluetoothDevice _device, Function(BluetoothConnection? connection) onConnected, Function(String message) onError) async {
  // if (!settingsUpdated){
  //   initialSettings(_device, onConnected, onError) ;
  //   return ;
  // }
  if (connection != null){
    print(connection?.isConnected);
    onConnected(connection);
  } else {
    await BluetoothConnection.toAddress(_device.address.toString()).then((_connection) {
      connection = _connection;
      startReadingParamsForeground();
      onConnected(connection);
    }).catchError((error) {
      connection = null;
      stopForegroundTask();
      print(error);
      onError("Error while connecting");
    });
    searching = false ;
  }
}

bool disconnect (){
  if (connection?.isConnected == true) {
    connection?.close();
    return true;
  } else {
    return false;
  }
}

Future<bool?> pairWithDevice(BluetoothDevice _device) async {
  return await _bluetooth.bondDeviceAtAddress(_device.address);
}

Future<bool> unpairWithDevice(BluetoothDevice _device) async {
  bool unpaired = false;
  try {
    bool? isUnpaired = await _bluetooth.removeDeviceBondWithAddress(_device.address);
    if (isUnpaired != null){
      unpaired = isUnpaired;
    }
  } catch (e) {
    unpaired = false ;
  }
  return unpaired;
}

Future<bool> isPaired (BluetoothDevice _device) async {
  BluetoothBondState state = await _bluetooth.getBondStateForAddress(_device.address);
  return state.isBonded;
}
Function(int requestCode, Map<String, String> serialResponse)? onReceive ;
bool initialedOnDataReceive = false ;
Future<void> setOnDataReceived(Function(int requestCode, Map<String, String> serialResponse) onReceiveData) async {
  onReceive = onReceiveData;
  if (!initialedOnDataReceive){
    initialOnDateReceive();
    initialedOnDataReceive = true ;
  }
}

Future<void> initialOnDateReceive() async {
  Map<String, String> blueResponses = Map();
  connection?.input?.listen((Uint8List data){
    Uint8List bytes = Uint8List.fromList(data.toList());
    String string = String.fromCharCodes(bytes);
    if (!string.contains('>')) {
      log['response'] = log['response'] != null ? log['response'].toString() + string : string;
    } else {
      log['response'] = log['response'] != null ? log['response'].toString() + string : string;
      Map<String, String> innerMap = Map();
      innerMap['response'] = log['response'].toString().contains(" ") ? log['response'].toString() : convertToByteString(log['response'].toString());
      innerMap['command'] = log['command'].toString();
      blueResponses = innerMap;
      log.clear();
      onReceive?.call(_requestCode, blueResponses);
      isWriting = false ;
      _requestCode = 999999999999999999;
      log.clear();
    }
  }).onDone(() {
    connection = null ;
    stopForegroundTask();
  });
}

Future<void> write(String command, int requestCode) async {
  if (!isWriting){
    _requestCode = requestCode ;
    log['command'] = command ;
    isWriting = true ;
    connection?.output.add(Uint8List.fromList(utf8.encode("$command\r\n"))) ;
    await connection?.output.allSent ;
  }
}



String convertToByteString (String text){
  var buffer = new StringBuffer();
  int every = 2 ; // Chars
  for (int i = 0; i < text.length; i++) {
    buffer.write(text[i]);
    var nonZeroIndex = i + 1;
    if (nonZeroIndex % every == 0 && nonZeroIndex != text.length) {
      buffer.write(' '); // Replace this with anything you want after each 2 chars
    }
  }

  return buffer.toString();
}



double volEff = 0.8322 ;
double fTime(x) => x / 1000 ;
double fRpmToRps(x) => x / 60 ;
double fMbarToKpa(x) => x / 1000 * 100 ;
double fCelciusToLelvin(x) => x + 273.15 ;
double fImap(rpm, pressMbar, tempC) {
  double v = (fMbarToKpa(pressMbar) / fCelciusToLelvin(tempC) / 2);
  return fRpmToRps(rpm) * v;
}
double fMaf(rpm, pressMbar, tempC) {
  double c = fImap(rpm, pressMbar, tempC);
  double v = c * volEff * 1.984 * 28.97;
  return v / 8.314;
}
double fFuel(rpm, pressMbar, tempC) {
  return (fMaf(rpm, pressMbar, tempC) * 3600) / (14.7 * 820);
}`

So far, I've designed a Bluetooth communication serial class and OBD-II value calculator, and so far I'm absolutely sure this class is working properly and tested it.

And at the bottom it puts the connection code in the foreground.


`import 'dart:convert';
import 'dart:ffi';
import 'dart:isolate';

import 'package:project/provider/bluetooth/OBDII.dart';
import 'package:project/provider/constants/retrofit.dart';
import 'package:project/provider/hive/hive_stores.dart';
import 'package:project/provider/retrofit/request.dart';
import 'package:project/provider/retrofit/request_response.dart';
import 'package:project/provider/settings.dart';
import 'package:project/ui/components/charts/param_data.dart';
import 'package:flutter_bluetooth_serial/flutter_bluetooth_serial.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:dio_http/dio_http.dart';
import 'package:http/http.dart' as http;
import 'package:share/share.dart';
import 'global_live_data.dart';

ReceivePort? _receivePort;

BluetoothConnection? connection ;

OBDII obd2 = OBDII();

void startCallback() {
  // The setTaskHandler function must be called to handle the task in the background.
  FlutterForegroundTask.setTaskHandler(ReadParametersTask());
}

class ReadParametersTask implements TaskHandler {
  bool initialReceivingData = false ;
  bool firstRun = true ;
  bool deletedConfigurationCommands = false ;
  int parameterIndex = 0 ;
  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
  }

  @override
  Future<void> onEvent(DateTime timestamp, SendPort? sendPort) async {
    await FlutterForegroundTask.updateService(
        notificationTitle: 'App is running in background ',
        notificationText: "Getting: ${OBDII.carParamsCommands[parameterIndex]}",
        callback: null
    );
    sendPort?.send(OBDII.carParamsCommands[parameterIndex]);
    if (parameterIndex < (OBDII.carParamsCommands.length - 1)){
      parameterIndex++;
    } else {
      parameterIndex = OBDII.obdConfigCommands.length ;
      firstRun = false ;
    }
  }

  @override
  Future<void> onDestroy(DateTime timestamp) async {
    await FlutterForegroundTask.clearAllData();
  }
}

Future<bool> stopForegroundTask() async {
  return await FlutterForegroundTask.stopService();
}

void dispose (){
  _receivePort?.close();
}

Future<bool> startReadingParamsForeground() async {
  await FlutterForegroundTask.saveData(key: 'connection', value: connection!);
  ReceivePort? receivePort;
  if (await FlutterForegroundTask.isRunningService) {
    receivePort = await FlutterForegroundTask.restartService();
  } else {
    receivePort = await FlutterForegroundTask.startService(
        notificationTitle: 'App is running in background',
        notificationText: 'Tap here for return to app.',
        callback: startCallback
    );
  }

  if (receivePort != null) {
    _receivePort = receivePort;
    _receivePort?.listen((message){
      handleMessage(message);
    });
    print("FGS :::::::: initialed");
    return true;
  }


  return false;
}

Future<void> handleMessage(message) async{
  setOnDataReceived((int requestCode, Map<String, String> serialResponse){
    String command = serialResponse["command"].toString();
    String response = serialResponse["response"].toString().replaceAll("\r", "").replaceAll(">", "").replaceAll("SEARCHING...", "").replaceAll("\n", "");
    calculateParam(command, response);
  });
  write(message, 999999999999999999);
}


Future <void> setParameter(String parameter, String raw, String data, int car) async {
  DateTime time = DateTime.now();
  String dateTime = "${time.toString().replaceAll(" ", "T")}" ;
  Dio _dio = Dio();
  RestClient _client = RestClient(_dio);
  Request<Parameter> _request = Request();
  _request.withClient(
      _client.setCarParameter(
          token,
          Parameter(car, parameter, raw, data, dateTime)
      ),
          (response){

      },
          (error){

      }
  );
}


void calculateParam(String command, String response){
  response = response.replaceAll("\r", "").replaceAll(">", "").replaceAll("SEARCHING...", "").replaceAll("\n", "");
  if (response.contains("UNABLE TO CONNECT")){
    return ;
  }
  switch (command){
    case "AT RV": {
      var voltage = response.replaceAll("v", "").replaceAll("V", "").replaceAll(" ", "");
      addVoltageToLive(voltage);
      HiveStore.getDefaultCarId().then((int car){
        if (car != 0){
          setParameter(command, voltage, voltage, car);
        }
      });
      break;
    }
    case "01 0C": {
      var rpm = (obd2.calculateRPM(command, response)).toString();
      addRPMToLive(rpm);
      HiveStore.getDefaultCarId().then((int car){
        if (car != 0){
          setParameter(command, response, rpm, car);
        }
      });
      break;
    }
    case "01 0D": {
      String speed = (obd2.calculateSpeed(command, response, returnBytes: 1)).toString();
      addSpeedToLive(speed);
      HiveStore.getDefaultCarId().then((int car){
        if (car != 0){
          setParameter(command, response, speed, car);
        }
      });
      break;
    }
    case "01 05": {
      var temp = (obd2.calculateTemp(command, response, returnBytes: 1)).toString();
      addTempToLive(temp);
      HiveStore.getDefaultCarId().then((int car){
        if (car != 0){
          setParameter(command, response, temp, car);
        }
      });
      break;
    }
    case "01 0B": {
      if (response != "NO DATA" && !response.contains("7F ${!command.contains(" ") ? command : command.split(" ")[0]}")){
        var fuelRate = (obd2.calculateFuelRate(command, response)).toString();
        addFuelRateToLive(fuelRate);
        HiveStore.getDefaultCarId().then((int car){
          if (car != 0){
            setParameter(command, response, fuelRate, car);
          }
        });
      } else {
        HiveStore.getDefaultCarId().then((int car){
          if (car != 0){
            setParameter(command, response, response, car);
          }
        });
      }
      break;
    }
    default: {
      break;
    }
  }
}


void addVoltageToLive (String voltage){
  var voltageString = 0.0 ;
  try {
    voltageString = double.parse(voltage);
    ecuConnection = true ;
    voltageLiveData.add(ParamData(DateTime.now(), voltageString));
    if (voltageLiveData.length > 7){
      voltageLiveData.removeAt(0);
    }
    for (int i  = 0; i < voltageLiveData.length ; i++){
      if ((voltageLiveData.length - 1) == i){
        return;
      }
      if (voltageLiveData[i].day.second == voltageLiveData[voltageLiveData.length - 1 ].day.second){
        voltageLiveData.removeAt(i);
        break ;
      }
    }
  } catch(e) {
    ecuConnection = false ;
  }
}
void addRPMToLive (String rpm){
  rpmLiveData.add(ParamData(DateTime.now(), double.parse(rpm).round().toDouble()));
  if (rpmLiveData.length > 7){
    rpmLiveData.removeAt(0);
  }
  for (int i  = 0; i < rpmLiveData.length ; i++){
    if ((rpmLiveData.length - 1) == i){
      return;
    }
    if (rpmLiveData[i].day.second == rpmLiveData[rpmLiveData.length - 1 ].day.second){
      rpmLiveData.removeAt(i);
      break ;
    }
  }
}

void addSpeedToLive (String speed){
  speedLiveData.add(ParamData(DateTime.now(), double.parse(speed)));
  if (speedLiveData.length > 7){
    speedLiveData.removeAt(0);
  }
  for (int i  = 0; i < speedLiveData.length ; i++){
    if ((speedLiveData.length - 1) == i){
      return;
    }
    if (speedLiveData[i].day.second == speedLiveData[speedLiveData.length - 1 ].day.second){
      speedLiveData.removeAt(i);
      break ;
    }
  }
}

void addTempToLive (String temp) {
  tempLiveData.add(ParamData(DateTime.now(), double.parse(temp)));
  if (tempLiveData.length > 7){
    tempLiveData.removeAt(0);
  }
  for (int i  = 0; i < tempLiveData.length ; i++){
    if ((tempLiveData.length - 1) == i){
      return;
    }
    if (tempLiveData[i].day.second == tempLiveData[tempLiveData.length - 1 ].day.second){
      tempLiveData.removeAt(i);
      break ;
    }
  }
}

void addFuelRateToLive (String temp) {
  fuelRateLiveData.add(ParamData(DateTime.now(), double.parse(temp)));
  if (fuelRateLiveData.length > 7){
    fuelRateLiveData.removeAt(0);
  }
  for (int i  = 0; i < fuelRateLiveData.length ; i++){
    if ((fuelRateLiveData.length - 1) == i){
      return;
    }
    if (fuelRateLiveData[i].day.second == fuelRateLiveData[fuelRateLiveData.length - 1 ].day.second){
      fuelRateLiveData.removeAt(i);
      break ;
    }
  }
}`

What I am sure of is that the connection value returns to the original state.
Because write () does not work after closing the program.

**Comment by Dev-hwang** [comment]
Even using this plugin does not prevent the destruction of the Dart code when the app is killed by the task manager. Dart code usually runs in the `main isolate`, and the `main isolate` is destroyed when the app exits. So global variables and dart classes in the `main isolate` are newly created every time the app starts.

This plugin takes advantage of foreground service. In the Android platform, the foreground service remains in the form of a notification even when the app is closed, helping to continue the work. So we call the `FlutterForegroundTask.startService` function to create a `new isolate`, and make that `new isolate` run in the foreground service. This way we can continue working on the `new isolate` even if the `main isolate` is destroyed.

The `ReceivePort` object returned when the `FlutterForegroundTask.startService` function is called is used to communicate messages between the 'main isolate' and the `new isolate`. If the app is restarted, it creates a new `main isolate`. In order to communicate with `new isolate` again, `FlutterForegroundTask.restartService` should be called to get a new `ReceivePort` object.

**Comment by alishe79** [comment]
Is there a specific solution to this problem here that can help me?
In general, is what I want to do possible?

**Comment by Dev-hwang** [comment]
It seems that the only way to do this is to add code to disconnect the bluetooth connection to the onDestroy function of the ReadParametersTask implementation class and restart the service when the app starts.

In addition, it would be better to put the global variables (connection, obd2) in the ReadParametersTask implementation class.

**Comment by Dev-hwang** [comment]
How about implementing in ReadParametersTask the part that connects the bluetooth device and handles the data?

It would be better to implement widgets to simply handle UI.

**Comment by alishe79** [comment]
Thanks for taking the time to answer this question.
