### ISSUE TITLE
ANdroid 14: Foreground service types are required 

### ISSUE THREAD

**Issue by timsar2** [Dev-hwang/flutter_foreground_task#300]
From android 14, The service will be stop after 6 hours if service type is not define.
1-service type must be declare in anroid manifest file 
2-servic type must be pass when going to startService

[https://developer.android.com/about/versions/14/changes/fgs-types-required#health](https://developer.android.com/about/versions/14/changes/fgs-types-required#health
)

**Comment by Dev-hwang** [comment]
@timsar2 

check [readme](https://github.com/Dev-hwang/flutter_foreground_task?tab=readme-ov-file#baby_chick-android)

You can specify the service type using the `android:foregroundServiceType` option as follows:

```xml
<!-- required -->
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

<!-- foregroundServiceType: dataSync -->
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />

<!-- foregroundServiceType: health -->
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_HEALTH" />

<!-- Warning: Do not change service name. -->
<service 
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="dataSync|health"
    android:exported="false" />
```

This plugin uses the [ServiceInfo.FOREGROUND_SERVICE_TYPE_MANIFEST](https://developer.android.com/reference/kotlin/android/content/pm/ServiceInfo#foreground_service_type_manifest) value to start the service, so you only need to specify the `android:foregroundServiceType` option.

https://github.com/Dev-hwang/flutter_foreground_task/blob/916289fd4fadbf1ebabf2c7715faf073504f4aa2/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt#L241
