### ISSUE TITLE
Breaking changes in minor version 8.16.0

### ISSUE THREAD

**Issue by Fleximex** [Dev-hwang/flutter_foreground_task#304]
Version 8.16.0 contains breaking changes. This is not expected according to semantic versioning. Almost everyone includes packages using a caret symbol `^` meaning every patch and minor update will be installed.

I.e.:
`flutter_foreground_task: ^8.14.0` is breaking now.

**Comment by Dev-hwang** [comment]
@Fleximex 

You are absolutely right. I seem to have misunderstood how the `flutter pub upgrade` command works. Users may encounter unintended bugs or code conflicts when upgrading a plugin's minor version. Thank you for the valuable advice. I will pay closer attention to versions moving forward.
