### ISSUE TITLE
ForegroundTask.stopService() not working when app is in its detached state

### ISSUE THREAD

**Issue by Cmon1007** [Dev-hwang/flutter_foreground_task#305]
Hi,
I hope this finds you well.
when using foreground task service it is working fine and its service is being stopped when the app is in its active state but when the app is in detached state its service is not stopping even if the app is closed fully.
Thanks

**Comment by Dev-hwang** [comment]
@Cmon1007 

Do you want the service to stop when the app is closed? If so, try setting the `stopWithTask` option as shown below:

```xml
<service 
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="dataSync"
    android:stopWithTask="true"
    android:exported="false" />
```

Could I ask where the ForegroundTask.stopService function is being called from? e.g. UI, TaskHandler, AppLifecycle

**Comment by Cmon1007** [comment]
ForegroundTask.stopService was called in AppLifecycle.
<service 
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="dataSync"
    android:stopWithTask="true"
    android:exported="false" />

adding  android:stopWithTask="true" solved the issue.

Thank you for the solution
