### ISSUE TITLE
When the app is closed, the notification does not disappear.

### ISSUE THREAD

**Issue by little-alei** [Dev-hwang/flutter_foreground_task#307]
Hello. When I click clear all button in the recent task view, the foreground task service notification still exists. Could you provide a solution to turn off the front desk service and its notifications when onDetachedFromActivity?

**Comment by little-alei** [comment]
I tried using AppLifecycleListener, calling foreground.stop () in onDetach, but it seems too late. The notification is not successfully shut down before the flutter engine is shut down

**Comment by Dev-hwang** [comment]
hello, @little-alei 

Do you want the service to stop when the app is closed? If so, try setting the `stopWithTask` option as shown below:

```xml
<service 
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="dataSync"
    android:stopWithTask="true"
    android:exported="false" />
```

**Comment by little-alei** [comment]
> hello, @little-alei
> 
> Do you want the service to stop when the app is closed? If so, try setting the `stopWithTask` option as shown below:
> 
> ```
> <service 
>     android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
>     android:foregroundServiceType="dataSync"
>     android:stopWithTask="true"
>     android:exported="false" />
> ```

Thank you very much. It works well
