### ISSUE TITLE
Error on ForegroundService.kt on compile flutter app

### ISSUE THREAD

**Issue by erueloi** [Dev-hwang/flutter_foreground_task#32]
When I compile the app with Visual Studio Code it gives me the following error:

e: C:\Projects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.5.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (210, 53): Unresolved reference: S
e: C:\Projects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.5.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (211, 13): Unresolved reference: setForegroundServiceBehavior
e: C:\Projects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.5.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (211, 55): Unresolved reference: FOREGROUND_SERVICE_IMMEDIATE

Thks.

**Comment by Dev-hwang** [comment]
https://github.com/Dev-hwang/flutter_foreground_task/issues/15#issue-974798638

Use the 'flutter clean' command as shown on this page.

**Comment by Ruud14** [comment]
I also have this issue and `flutter clean` doesn't seem to fix it.
I tried running flutter clean multiple times, together with the other steps mentioned in #15 But they don't work for my project.

I also tried it on the [example](https://github.com/Dev-hwang/flutter_foreground_task/tree/master/example), where I first changed the pubspec.yaml file to not get this package from ../, and there, indeed, the issue was fixed after running `flutter clean`. 

Do you have any clue why this fix doesn't work on my project?

**Comment by Dev-hwang** [comment]
Can you try setting the `compileSdkVersion` and `targetSdkVersion` values ​​to `31` in the app level `build.gradle` file?

```gradle
android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.pravera.flutter_foreground_task_example"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    ...
}
```

**Comment by Dev-hwang** [comment]
@erueloi, @Ruud14

Can you try setting the `compileSdkVersion` and `targetSdkVersion` values ​​to `31` in the app level `build.gradle` file?

```gradle
android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.pravera.flutter_foreground_task_example"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    ...
}
```

And add the exported option to the MainActivity tag of the AndroidManifest file.

``` 
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true"> // here
```

**Comment by Ruud14** [comment]
That worked!
Thanks a lot!

**Comment by rafeira** [comment]
I fixed this error but another one came up.
Can you help me?


Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /home/rafeira/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.1/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (215, 53): Unresolved reference: S
e: /home/rafeira/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.1/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (216, 13): Unresolved reference: setForegroundServiceBehavior
e: /home/rafeira/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.1/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (216, 55): Unresolved reference: FOREGROUND_SERVICE_IMMEDIATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_foreground_task:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
Running Gradle task 'assembleRelease'...                           60.6s
Gradle task assembleRelease failed with exit code 1

**Comment by erueloi** [comment]
Thks, it has worked for me too! ^^
