### ISSUE TITLE
What is wakeUpScreen supposed to do?

### ISSUE THREAD

**Issue by madatr** [Dev-hwang/flutter_foreground_task#39]
Hi, thanks for the solid package that is very useful.

void function() => FlutterForegroundTask.wakeUpScreen();

is it supposed to just light up the screen if it is off or is it supposed wake up the up (the opposite of minimizeApp)?

Currently, minimizeApp works and puts the app in the background but wakeUpScreen does nothing for me

Thanks,

**Comment by Dev-hwang** [comment]
You can turn on the screen of a device that is turned off with the `wakeUpScreen` function. This only works on the Android platform.

If the function still does not work, check if the `android.permission.WAKE_LOCK` permission is added to the `AndroidManifest.xml` file.

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

**Comment by madatr** [comment]
what do you mean by wakeUpScreen? what is it supposed to do?

**Comment by Dev-hwang** [comment]
When a notification arrives when the device's screen is off, it has the same effect as briefly turning on the screen. 

You can wake up the screen to let the user know that the service is running. Not only that, it is also used to solve the [Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby?hl=us) of the Android platform. It will use more battery, but you will be able to process or send data to the server without delay.

**Comment by madatr** [comment]
Aha, I see.

I was expecting a different behaviour, maybe it would be a good idea to include you comment in the documentation.

Thanks my man

**Comment by Dev-hwang** [comment]
You might be able to work around 'Doze mode' using this function, but that's not a good idea. It is best to turn off the battery optimization option by calling the `requestIgnoreBatteryOptimization` function.

**Comment by madatr** [comment]
I already use ignoreBatteryOptimisation because I need to keep sending the user's location to an API.

I am trying to wake up my app whenever an order arrives so that the user can take an action. 

Probably going to develop some native code to have a call like UI to have the user either accept or reject the order.
