### ISSUE TITLE
flutter_foreground_task

### ISSUE THREAD

**Issue by alsheikhaminulislam** [Dev-hwang/flutter_foreground_task#40]
can i use socket.io/ node server/ tcp server 
with flutter_foreground_task
if not then 
fackebook/messenger/viber/whatsup
 how to user  ??

**Comment by Dev-hwang** [comment]
Server communication is possible inside the TaskHandler implementation class. Instead, it is recommended to initialize the plugin in the onStart function of the TaskHandler implementation class.
