### ISSUE TITLE
IOS Notification Issue when updating notification using updateService method

### ISSUE THREAD

**Issue by AbdulBariOsitech** [Dev-hwang/flutter_foreground_task#45]
using
flutter_foreground_task: 3.5.2
flutter: 2.8.0
Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"

I am running a timer from onStart() function of the TaskHandler 
In the timer event, when I am updating the notification text using FlutterForegroundTask.updateService(), a new notification generates instead of updating the current one. 

**The issue only exists in IOS**

while doing the same in Android, it just updates the current notification, instead of generating the new one

Here is the sample code of TaskHandler to reproduce the issue.

What I am assuming, is the same behavior that is to update the current notification, just update the text  instead of updating the whole notification. OR Similar behavior to Android

Everything else is running fine!

```
class ForegroundTaskHandler implements TaskHandler {
  @override
  Future<void> onStart(DateTime timestamp, SendPort sendPort) async {
    int maxTime = await FlutterForegroundTask.getData(key: 'maxTime');

    Timer.periodic(const Duration(seconds: 1), (timer) async {
      if (maxTime > 0) {
        sendPort.send(--maxTime);
        FlutterForegroundTask.updateService(
          notificationTitle: 'Time Remaining',
          notificationText:
              '${(maxTime ~/ 60).toString().padLeft(2, '0')}:${(maxTime % 60).toString().padLeft(2, '0')}',
        );
      } else {
        timer.cancel();
      }
    });
  }

  @override
  Future<void> onEvent(DateTime timestamp, SendPort sendPort) async {}

  @override
  Future<void> onDestroy(DateTime timestamp) async {
  }

  @override
  void onButtonPressed(String id) {
  }
}

```

Please have a look into this, or provide some guideline if I am doing it the wrong way.

Feel free to ask more information if needed!

**Comment by AbdulBariOsitech** [comment]
@Dev-hwang

**Comment by Dev-hwang** [comment]
I understand that you can't create foreground service notifications on the iOS platform like on the Android platform. When I update the notification on the iOS platform, the new creation is what I was expecting. 

There doesn't seem to be a way to fix this at this time. If there is a good way, please suggest.

**Comment by Dev-hwang** [comment]
I know that it is not possible to create a foreground service notification on an iOS platform like on an Android platform. Updating the notification on the iOS platform, the new creation was as expected.

There doesn't seem to be a way to fix this at this time. If there is a good way, please suggest.
