### ISSUE TITLE
Notification Icon is not shown properly

### ISSUE THREAD

**Issue by aeropagz** [Dev-hwang/flutter_foreground_task#46]
Hello,

I have the problem that the notification icon is not shown. Just an grey circle is displayed. 

I am using the launcher icon as notification icon. So I just changed the Icons and not the example code.

```
iconData: const NotificationIconData(
          resType: ResourceType.mipmap,
          resPrefix: ResourcePrefix.ic,
          name: 'launcher',
        )
```

in every mipmap folder is a ic_launcher.png file.

**Comment by nicop2000** [comment]
same problem here

**Comment by Dev-hwang** [comment]
Is this a problem with the simulator? Or is this a problem with real devices as well?

**Comment by aeropagz** [comment]
Oh, I tried on a real device and it's working there. Thnx.
