### ISSUE TITLE
Problem with iOS Bridging Header

### ISSUE THREAD

**Issue by nicop2000** [Dev-hwang/flutter_foreground_task#47]
I always get this error when I try to run my app on an iOS device:
Runner/Runner-Bridging-Header.h:2:9: error: 'flutter_foreground_task/FlutterForegroundTaskPlugin.h' file not found
    #import <flutter_foreground_task/FlutterForegroundTaskPlugin.h>
I tried clean build folder, pod deintegrate, flutter clean, flutter pub get, pod install
nothing worked

**Comment by Dev-hwang** [comment]
Remove the `.symlinks` and `Podfile.lock` files from the ios folder and try to build again?

![스크린샷 2022-01-06 오전 9 00 08](https://user-images.githubusercontent.com/47127353/148307029-1975c243-fc8a-4dcf-8b1a-b574c0e0e0c6.png)

**Comment by nicop2000** [comment]
thx for your quick repsonse, but deleting those didn't change anything :c

**Comment by Dev-hwang** [comment]
This is the first time I've seen this problem. Now, I created a project for each `Objective-C` and `Swift` and tested it, but this problem did not occur. 

Please create a new project and check if this same problem occurs. If it works properly in a new project, it seems to be a problem with the `Runner-Bridging-Header.h` recognition or a problem with the build cache.

**Comment by nicop2000** [comment]
I tried it with another project, but the same error occurred :c
