### ISSUE TITLE
Add SendPort on onButtonPressed callback

### ISSUE THREAD

**Issue by hendy3617** [Dev-hwang/flutter_foreground_task#48]
Hello, is it possible for this plugin to add SendPort object on onButtonPressed callback as a parameter? I'm having a notification button that is supposed to communicate with the main isolate when pressed, but TaskHandler doesn't seem to have this object by default that this can only be obtained in certain callback like onEvent().

Thank you.

**Comment by Dev-hwang** [comment]
Create a variable in the `TaskHandler` implementation class to hold the `SendPort` object. Then initialize the variable in the `onStart` function.

**Comment by Dev-hwang** [comment]
Create a variable in the TaskHandler implementation class to hold the SendPort object. Then initialize the above variable in the `onStart` function. This way you can also use the SendPort object in the `onEvent` function.
