### ISSUE TITLE
Not able to access Pedometer stream in foreground service

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#5]
While running the foreground service I want to access the pedometer stream. Here I am using [pedometer](https://pub.dev/packages/pedometer) package which exposes a stream for accessing steps of the device. When I was using [flutter_foreground_service_plugin](https://pub.dev/packages/flutter_foreground_service_plugin) I did not face any issue accessing the stream. But using this plugin I am facing an issue related to ServicesBinding.defaultBinaryMessenger. I also placed 
`  WidgetsFlutterBinding.ensureInitialized();` in `main.dart` but it is still giving me this error. It would be a great help if you can look into it cause I don't want to switch back to [flutter_foreground_service_plugin](https://pub.dev/packages/flutter_foreground_service_plugin) since this plugin is quite awesome and well documented.

> Code

  Stream<StepCount> _stepCountStream = Pedometer.stepCountStream;
  final StepCount steps = await _stepCountStream.first;

> Error

```
E/flutter (23365): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (23365): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (23365): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (23365): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:97:7)
E/flutter (23365): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:110:4)
E/flutter (23365): #2      EventChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:512:62)
E/flutter (23365): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:532:7)
E/flutter (23365): #4      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:531:64)
E/flutter (23365): #5      _runGuarded (dart:async/stream_controller.dart:773:24)
E/flutter (23365): #6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter (23365): #7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
E/flutter (23365): #8      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (23365): #9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter (23365): #10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter (23365): #11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter (23365): #12     Stream.first (dart:async/stream.dart:1211:14)
E/flutter (23365): #13     periodicTaskFun (package:realfit/core/background/foreground_service.dart:70:50)
E/flutter (23365): #14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
E/flutter (23365): #15     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (23365): #16     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23365): #17     _runZoned (dart:async/zone.dart:1788:10)
E/flutter (23365): #18     runZonedGuarded (dart:async/zone.dart:1776:12)
E/flutter (23365): #19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
E/flutter (23365): #20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (23365): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (23365): 

```

**Comment by Dev-hwang** [comment]
I would like to know at what point this problem occurs. When I tested this didn't happen.

![image](https://user-images.githubusercontent.com/47127353/124203049-c96c1800-db16-11eb-8943-2891b867eed4.png)

![image](https://user-images.githubusercontent.com/47127353/124203071-da1c8e00-db16-11eb-8f3d-373536a41448.png)

**Comment by Dev-hwang** [comment]
@darshansatra1 

Or try this way~

![image](https://user-images.githubusercontent.com/47127353/124206337-20292000-db1e-11eb-9709-17c31bb3837a.png)

![image](https://user-images.githubusercontent.com/47127353/124206354-2a4b1e80-db1e-11eb-9b1d-68907760a7a2.png)

**Comment by darshansatra1** [comment]
Yess the issue is gone now. The problem was I didn't wrap my code around `FlutterForegroundTask.initDispatcher`. Thank you

**Comment by Dev-hwang** [comment]
@darshansatra1 

You can easily subscribe to stream by upgrading the flutter_foreground_task plugin and using this method.

![image](https://user-images.githubusercontent.com/47127353/124239270-7ca73200-db54-11eb-889f-6bee2e06e9d4.png)

![image](https://user-images.githubusercontent.com/47127353/124239323-8a5cb780-db54-11eb-9f5c-4ba9bb27dd06.png)
