### ISSUE TITLE
Considering android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS support on Android

### ISSUE THREAD

**Issue by MrCsabaToth** [Dev-hwang/flutter_foreground_task#51]
I compared https://pub.dev/packages/flutter_background and https://pub.dev/packages/flutter_foreground_task and I wonder if it was possible to add support for android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS permissions on Android. Not sure if https://stackoverflow.com/questions/44862176/request-ignore-battery-optimizations-how-to-do-it-right is something to watch out for (Android 6 is API 23, currently the package min SDK is 21 so theoretically yes). I haven't looked deeper into https://github.com/JulianAssmann/flutter_background yet to see what else is needed for that permission.

**Comment by Dev-hwang** [comment]
The function to request the `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission is already implemented.

https://github.com/Dev-hwang/flutter_foreground_task#lollipop-requestignorebatteryoptimization-android

**Comment by MrCsabaToth** [comment]
Gotcha. I see that https://github.com/Dev-hwang/flutter_foreground_task/blob/master/android/src/main/kotlin/com/pravera/flutter_foreground_task/utils/ForegroundServiceUtils.kt has the `ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS` mechanisms and the host app has to add the `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`
