### ISSUE TITLE
How to perform specific function with  flutter_foreground_task

### ISSUE THREAD

**Issue by vaartatechnologies** [Dev-hwang/flutter_foreground_task#52]
Hi, apology for being dumb and asking this question here.

I am using Flutter Telephony plugin which works fine (listens to incoming SMS). But it only works when app is in foreground for some reason. So I decided to use this plugin to listen to incoming SMS through foreground task, but don't know where to start.

So far I have been able to get flutter_foreground_task working as in example, but which part of code in this plugin will handle **Flutter Telephony** events?

Please help.

**Comment by Dev-hwang** [comment]
Looking at the [telephony](https://pub.dev/packages/telephony#listen-to-incoming-smshttpsshounakmulaygitbookiotelephonylisten-incoming-sms) plugin, it seems that background processing is already included.

```dart
backgrounMessageHandler(SmsMessage message) async {
	// Handle background message	
}

telephony.listenIncomingSms(
	onNewMessage: (SmsMessage message) {
		// Handle message
	},
	onBackgroundMessage: backgroundMessageHandler
);
```

Would you like to go to the [Telephony issues](https://github.com/shounakmulay/Telephony/issues) page and check it out?

**Comment by vaartatechnologies** [comment]
Thanks for taking time and replying.

I have already tried that and not working for some reason.

Is there a way to run some task through flutter_foreground_task though? For example, showing a toast every 5 seconds.

**Comment by Dev-hwang** [comment]
I tested using the `telephony` plugin and the `listenIncomingSms` function doesn't seem to work properly with this plugin. But the `sendSms` function seems to work fine. To view a sample app, go to the address below.

https://github.com/Dev-hwang/telephony_sample

**Comment by vaartatechnologies** [comment]
I would like to thank you so much for taking the pain for going through that plugin and created that sample app.

Duplicate of # and the listenIncomingSms function doesn't seem to work properly with this plugin

Is it it possible with `flutter_foreground_task` to listen to data change or new data inserted in Firestore?

**Comment by Dev-hwang** [comment]
I haven't tested it, but looking at the implementation of the `cloud_firestore` plugin, it looks like it could be used with this plugin.
