### ISSUE TITLE
WillStartForegroundTask causing shared preference data clean

### ISSUE THREAD

**Issue by rahulmawana** [Dev-hwang/flutter_foreground_task#53]
When we are using WillStartForegroundTask, then on hot restart of app (R) shared preference data is getting clean, it is not getting persisted, I am using https://pub.dev/packages/shared_preferences

**Comment by rahulmawana** [comment]
clearAllData was main culprit, Not any issue or bug

**Comment by bhavin-concetto** [comment]
@rahulmawana what is the solution? Clear only specific data?

**Comment by rahulmawana** [comment]
> @rahulmawana what is the solution? Clear only specific data?

correct, probably you need to use await FlutterForegroundTask.removeData('your_desired_key');
