### ISSUE TITLE
Notification Permission & Geolocator issues

### ISSUE THREAD

**Issue by cto-leaps** [Dev-hwang/flutter_foreground_task#54]
While testing your great plugin to track location with Geolocator, I inadvertently denied permissions.
Now, no matter if I uninstall the app, I still get Permission denied by default and the foreground service doesn't work.
How can I ensure that notifications permissions are allowed before launching the service?

I have honestly been struggling to get Location tracking working on Android and using your plugin seemed to be the right solution, but I don't seem to be able to get it to work and I think the notification issue might be the reason...

**Comment by cto-leaps** [comment]
Also, using your example code for Geolocator Stream, I only seem to get one event when Foreground service is started, then none after that, even though I am walking.


`// The callback function should always be a top-level function.
void startCallback() {
  // The setTaskHandler function must be called to handle the task in the background.
  FlutterForegroundTask.setTaskHandler(FirstTaskHandler());
}

class FirstTaskHandler extends TaskHandler {
  StreamSubscription<Position>? streamSubscription;

  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    LocationSettings locationSettings = AndroidSettings(
      accuracy: LocationAccuracy.high,
      distanceFilter: 10,
      // intervalDuration: const Duration(seconds: 1),
    );

    final positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings);
    streamSubscription = positionStream.listen((event) {
      // Update notification content.
      FlutterForegroundTask.updateService(
          notificationTitle: 'Current Position',
          notificationText:
              '${event.latitude}, ${event.longitude} - Alt: ${event.altitude}');

      // Send data to the main isolate.
      sendPort?.send(event);
    });
  }

  @override
  Future<void> onEvent(DateTime timestamp, SendPort? sendPort) async {}

  @override
  Future<void> onDestroy(DateTime timestamp) async {
    await streamSubscription?.cancel();
  }

  @override
  void onButtonPressed(String id) {
    // Called when the notification button on the Android platform is pressed.
  }
}`

**Comment by cto-leaps** [comment]
Nevermind, I finally found a way to do this.
Thanks!

**Comment by aryanA101a** [comment]
> Nevermind, I finally found a way to do this. Thanks!

Hey, I am in the same hole. Please let me know :how you solved it?
