### ISSUE TITLE
Is it possible to reuse ReceivePort on Service restart?

### ISSUE THREAD

**Issue by busslina** [Dev-hwang/flutter_foreground_task#57]
I assume that when Flutter activity gets killed, all Dart side app state gets erased. The foreground service keeps running, and when activity gets opened again it reconnects with the ForegroundService via restarting it, geting a new ReceivePort.

Wouldn't be possible to not restart the Service and saving or rebuild the ReceivePort (saving info in the Service itself, or in the Android application, or iOS)?

Thank you

**Comment by Dev-hwang** [comment]
Use the `FlutterForegroundTask.receivePort` getter function.

https://github.com/Dev-hwang/flutter_foreground_task/issues/44
