### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences

### ISSUE THREAD

**Issue by rahulmawana** [Dev-hwang/flutter_foreground_task#59]
I am getting "(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences" as trying to set any value by using 

await FlutterForegroundTask.saveData(key: 'customData', value: 'hello');
I am using version 3.5.5
following is my flutter doctor:

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-IN)
    • Flutter version 2.10.1 at J:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at J:/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\users\Rahul\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • Java binary at: J:/android-studio-installation\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at J:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at J:\android-studio-installation
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at J:/android-studio-installation
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = J:/android-studio-installation
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.64.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • ONEPLUS A6000 (mobile) • 192.168.0.2:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)      • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1466]
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 97.0.1072.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

==========
I am attaching my sample APP, you can check over there.

https://github.com/rahulmawana/flutter_sample_app/tree/main

Thanks
@Dev-hwang

**Comment by liemfs** [comment]
I'm facing similar issue

**Comment by rahulmawana** [comment]
> I'm facing similar issue

have you managed to resolve it?

**Comment by liemfs** [comment]
> > I'm facing similar issue
> 
> have you managed to resolve it?

Yes I have
But I think this is just temporary solution

Just add this line on pubspec.yaml

```
dependency_overrides:
  shared_preferences_android: 2.0.10
```

**Comment by smedasn** [comment]
I have the same issue. is it possible to register specific plugins for the foreground isolate?

**Comment by Dhirajraje** [comment]
Same issue with Ios. Any solutions?

**Comment by liemfs** [comment]
> I have the same issue. is it possible to register specific plugins for the foreground isolate? To reproduce you can for example run getTemporaryDirectory() (path_privider package) inside the foreground service isolate

Follow my temporary solution

> Same issue with Ios. Any solutions?

For iOS, please do this
```
dependency_overrides:
  shared_preferences_ios: 2.0.9
```

**Comment by liemfs** [comment]
Actually, this is nothing todo with this flutter_foreground_task, but rather shared_preferences itself, this link will tell you how this issues appear
https://github.com/flutter/flutter/issues/99155#issuecomment-1052023743

**Comment by spalenzuela** [comment]
> 

Same issue, any ideas?

**Comment by Dhirajraje** [comment]
> Actually, this is nothing todo with this flutter_foreground_task, but rather shared_preferences itself, this link will tell you how this issues happens [flutter/flutter#99155 (comment)](https://github.com/flutter/flutter/issues/99155#issuecomment-1052023743)
> 
> You can follow solutions provided in the link, or just add dependecy_overrides over shared_preferences_android or shared_preferences_ios

This worked for me.

**Comment by smedasn** [comment]
> > I have the same issue. is it possible to register specific plugins for the foreground isolate? To reproduce you can for example run getTemporaryDirectory() (path_privider package) inside the foreground service isolate
> 
> Follow my temporary solution
> 
> > Same issue with Ios. Any solutions?
> 
> For iOS, please do this
> 
> ```
> dependency_overrides:
>   shared_preferences_ios: 2.0.9
> ```

this is not about only this plugin. it does not work with the most plugins. for example Hive, Scraper. The workaround for shared preferences works. but it would be nice to make every plugin work which does not requiere activity lifecycles

**Comment by Brunobnahorny** [comment]
Hi, @Dev-hwang 

 Is it fixed ?
