### ISSUE TITLE
Using example code inside my existing app: onEvent in TaskHandler never gets called.

### ISSUE THREAD

**Issue by irjayjay** [Dev-hwang/flutter_foreground_task#62]
Hi!
I've been struggling to get onEvent to be called for the last two days.
The onStart also doesn't get called.
I get the onDestroy to call when I stop the service as well as onButtonPressed when pressing buttons.

It worked fine in a blank app, but on my other existing app it just never gets called.  Neither the first or second TaskHandlers have onEvent called ever.

I've added the service to the manifest file,  as well as WAKE_LOCK and FOREGROUND_SERVICE permissions.

Will add the example code I'm using.

**Comment by irjayjay** [comment]
`
import 'dart:isolate';

import 'package:flutter/material.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';

// The callback function should always be a top-level function.
void startCallback() {
  // The setTaskHandler function must be called to handle the task in the background.
  FlutterForegroundTask.setTaskHandler(FirstTaskHandler());
}

class FirstTaskHandler extends TaskHandler {
  int updateCount = 0;

  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    // You can use the getData function to get the data you saved.
    final customData =
        await FlutterForegroundTask.getData<String>(key: 'customData');
    print('customData: $customData');
  }

  @override
  Future<void> onEvent(DateTime timestamp, SendPort? sendPort) async {
    FlutterForegroundTask.updateService(
        notificationTitle: 'FirstTaskHandler',
        notificationText: timestamp.toString(),
        callback: updateCount >= 10 ? updateCallback : null);

    // Send data to the main isolate.
    sendPort?.send(timestamp);
    sendPort?.send(updateCount);

    updateCount++;
  }

  @override
  Future<void> onDestroy(DateTime timestamp) async {
    // You can use the clearAllData function to clear all the stored data.
    await FlutterForegroundTask.clearAllData();
  }

  @override
  void onButtonPressed(String id) {
    // Called when the notification button on the Android platform is pressed.
    print('onButtonPressed >> $id');
  }
}

void updateCallback() {
  FlutterForegroundTask.setTaskHandler(SecondTaskHandler());
}

class SecondTaskHandler extends TaskHandler {
  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {}

  @override
  Future<void> onEvent(DateTime timestamp, SendPort? sendPort) async {
    FlutterForegroundTask.updateService(
        notificationTitle: 'SecondTaskHandler',
        notificationText: timestamp.toString());

    // Send data to the main isolate.
    sendPort?.send(timestamp);
  }

  @override
  Future<void> onDestroy(DateTime timestamp) async {}
}

class NotificationExample extends StatefulWidget {
  const NotificationExample({Key? key}) : super(key: key);

  @override
  _NotificationExampleState createState() => _NotificationExampleState();
}

class _NotificationExampleState extends State<NotificationExample> {
  ReceivePort? _receivePort;

  Future<void> _initForegroundTask() async {
    await FlutterForegroundTask.init(
      androidNotificationOptions: AndroidNotificationOptions(
        channelId: 'notification_channel_id',
        channelName: 'Foreground Notification',
        channelDescription:
            'This notification appears when the foreground service is running.',
        channelImportance: NotificationChannelImportance.LOW,
        priority: NotificationPriority.LOW,
        iconData: const NotificationIconData(
          resType: ResourceType.mipmap,
          resPrefix: ResourcePrefix.ic,
          name: 'launcher',
        ),
        buttons: [
          const NotificationButton(id: 'sendButton', text: 'Send'),
          const NotificationButton(id: 'testButton', text: 'Test'),
        ],
      ),
      iosNotificationOptions: const IOSNotificationOptions(
        showNotification: true,
        playSound: false,
      ),
      foregroundTaskOptions: const ForegroundTaskOptions(
        interval: 5000,
        autoRunOnBoot: true,
        allowWifiLock: true,
      ),
      printDevLog: true,
    );

    FlutterForegroundTask.init
  }

  Future<bool> _startForegroundTask() async {
    // You can save data using the saveData function.
    await FlutterForegroundTask.saveData(key: 'customData', value: 'hello');

    ReceivePort? receivePort;
    if (await FlutterForegroundTask.isRunningService) {
      receivePort = await FlutterForegroundTask.restartService();
    } else {
      receivePort = await FlutterForegroundTask.startService(
        notificationTitle: 'Foreground Service is running',
        notificationText: 'Tap to return to the app',
        callback: startCallback,
      );
    }

    if (receivePort != null) {
      _receivePort = receivePort;
      _receivePort?.listen((message) {
        if (message is DateTime) {
          print('receive timestamp: $message');
        } else if (message is int) {
          print('receive updateCount: $message');
        }
      });

      return true;
    }

    return false;
  }

  Future<bool> _stopForegroundTask() async {
    return await FlutterForegroundTask.stopService();
  }

  @override
  void initState() {
    super.initState();
    _initForegroundTask();
  }

  @override
  void dispose() {
    _receivePort?.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _buildContentView();
  }

  Widget _buildContentView() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          _buildTestButton('start', onPressed: _startForegroundTask),
          _buildTestButton('stop', onPressed: _stopForegroundTask),
        ],
      ),
    );
  }

  Widget _buildTestButton(String text, {VoidCallback? onPressed}) {
    return ElevatedButton(
      child: Text(text),
      onPressed: onPressed,
    );
  }
}

`

**Comment by irjayjay** [comment]
Basically the same as your example, except I converted it to a standalone widget and inserted it into my app.

**Comment by etimes2008** [comment]
me too

**Comment by irjayjay** [comment]
I have now copied the exact code from my empty Flutter project over to my existing app and it still doesn't call the onEvent method. 

This leeds me to believe it's a configuration problem. I'm gonna double check the manifest file.

**Comment by irjayjay** [comment]
SOLVED!
After heaps of time wasted on this, I narrowed it down to the pubspec.lock file. One of the dependencies had been updated recently, which seems to have broken this project.

shared_preferences_android
version: "2.0.11" should be version 2.0.10 to make this library work again. Seems they introduced breaking changes with their update.

Add the following to your pubspec.yaml to solve for now:
```
dependency_overrides:
  shared_preferences_android: "2.0.10"
```

**Comment by irjayjay** [comment]
@Dev-hwang, don't know if you want to release a fix for this, hard coding the version of shared preferences the plugin uses?

**Comment by cheeco83** [comment]
I had the same problem, and I found this post to fix the problem without downgrading the version. I confirm it fixes the problem: 
https://github.com/flutter/flutter/issues/98473#issuecomment-1041895729

in the pubspec.yaml you include the following: shared_preferences_android: ^2.0.11

and in your sourcecode, you put:

import 'package:shared_preferences_android/shared_preferences_android.dart';
... 
  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    SharedPreferencesAndroid.registerWith();
...

I hope this helps!
