### ISSUE TITLE
My Foreground service running automatically when my phone restart

### ISSUE THREAD

**Issue by barangungor** [Dev-hwang/flutter_foreground_task#64]
My foreground service running normal when i start from my application but  When I restart my device it running automatically, I want to prevent the foreground service from starting by itself.

**Comment by taimoor522** [comment]
@barangungor initiate FlutterForegroundTask and set foregroundTaskOptions as follows:

```
    foregroundTaskOptions: const ForegroundTaskOptions(
      interval: 5000,
      autoRunOnBoot: true,
      allowWifiLock: true,
)
```

**Comment by Dev-hwang** [comment]
And if you want to terminate the service as well when the app is closed, declare the service as follows:

```xml
<service
        android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
        android:stopWithTask="true" />
```
