### ISSUE TITLE
Problem with ForegroundService.kt

### ISSUE THREAD

**Issue by almogbrooker** [Dev-hwang/flutter_foreground_task#67]
Tried to upgrade the kotlin but didnt work

`e: [/home/almog/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt](): (326, 50): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: [/home/almog/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt](): (344, 4): 'error' overrides nothing
e: [/home/almog/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt](): (360, 52): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: [/home/almog/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt](): (366, 4): 'error' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_foreground_task:compileDebugKotlin'.
> Compilation error. See log for more details`

Thanks

**Comment by Dev-hwang** [comment]
https://github.com/Dev-hwang/flutter_foreground_task/issues/15

Try using the `flutter clean` command.

**Comment by Dev-hwang** [comment]
Upgrading to version 3.7.3 can solve this problem.

```yaml
dependencies:
  flutter_foreground_task: ^3.7.3
```
