### ISSUE TITLE
use camera while the app is in foreground

### ISSUE THREAD

**Issue by X-SLAYER** [Dev-hwang/flutter_foreground_task#68]
is it possible to use the camera while the app is in the foreground 
like this 

![Screenshot_20220321-172928 (1)](https://user-images.githubusercontent.com/22800380/159309402-5fb5f198-45b5-4116-9a17-4b877aec8968.png)

![Screenshot_20220321-172940](https://user-images.githubusercontent.com/22800380/159309465-0b427903-e22f-49be-aff7-8fa57caec442.png)

**Comment by Dev-hwang** [comment]
It is difficult to implement the above functions using this plugin. You must implement that functionality directly in your Android native code.
