### ISSUE TITLE
sample not working with latest version of flutter

### ISSUE THREAD

**Issue by smedasn** [Dev-hwang/flutter_foreground_task#70]
failing with:

Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use

[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.66.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by Dev-hwang** [comment]
Upgrading to version 3.7.3 can solve this problem.

```yaml
dependencies:
  flutter_foreground_task: ^3.7.3
```
