### ISSUE TITLE
Getting Data in between the foreground task isolate and the rest of the app

### ISSUE THREAD

**Issue by BJRichardsAZ** [Dev-hwang/flutter_foreground_task#71]
Currently in our app we are using a repository -> cubit -> UI layer architecture to create and structure all of the different features we are providing to our users. We are attempting to use foreground task to keep our app reliably counting steps in the background through the use of the pedometer package. The pedometer package provides a stream of the entire amount of steps counted since it is first initialized on the users phone; in order to provide the user with a clearer picture of the steps taken during that day, we are using the hive database plug in for flutter to store step counts with timestamps in order to present the step data in a more useful way to the user. All of this code is done inside of a lazy singleton "repository", and we can access these methods from anywhere in the app using injection and then GetIt package. However when trying to get a hold of these methods inside the code we are running for the callback of the foreground task, we get an exception thrown that our factory has not been registered. I'm assuming that this is because inside this isolate we are unable to access our singleton which has been registered in the main part of the app outside of the foreground task. I decided to try taking a different approach by seeing if I could at least process the steps and store them in our Hive database directly so that the other portion of the app could also access these values. That way both the foreground process would run and process the steps when the app is closed; and when the app is open and the user is checking their step count they get an accurate depiction of the steps they have taken that day. This however, also ran into some issues as it seems the isolate also has trouble locating the hive box which has been initialized outside of the isolate as well. Does anyone have any ideas on how I might be able to make this work with in our current structure? What we ultimately need to achieve is the ability to process the data from the raw pedometer stream and store it inside the foreground task, and then we need to be able to access this stored data directly in the pages where we will present that data to the viewer.

We have taken all the functions relating to the foreground task and written them in their own file, "foregroundTask.dart" and are calling the methods where they are needed in the app. In this case we are passing a ReceivePort stored in the cubit of the Step Counter page into the startForegroundTask message when it is called.

    Future<bool> startForegroundTask(ReceivePort? _receivePort) async {
      ReceivePort? receivePort;
      if (await FlutterForegroundTask.isRunningService) {
        receivePort = await FlutterForegroundTask.restartService();
      } else {
        print('foreground started');
        receivePort = await FlutterForegroundTask.startService(
           notificationTitle: 'Step Count',
           notificationText: 'test!',
           callback: startCallback);
      }

Callback for the foreground task, located within the "foregroundTask.dart file, listening to the raw pedometer stream and trying to call our countTodaySteps function from our "health" repository in our library:

     class CountStepsHandler extends TaskHandler {
       final StreamValue<int> _steps = StreamValue();
       StreamSubscription<StepCount>? streamSubscription;
       DateTime get todayDate => DateUtils.dateOnly(DateTime.now());

      @override
      Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
        SharedPreferencesAndroid.registerWith();
        final stepStream = Pedometer.stepCountStream;
        streamSubscription = stepStream.listen((steps) async {
          int todaySteps = getIt<HealthRepository>().countTodaySteps(steps);
          FlutterForegroundTask.updateService(
              notificationTitle: 'StepCount!',
              notificationText:
                  '${todaySteps} steps taken today!');

          // Send data to the main isolate.
          print('Steps: ${steps}');
          sendPort?.send(steps);
        });
      }
      
The "countTodaySteps" function which we are trying to call within the foreground task to process the amount of steps taken that day based on the amount from the pedometer stream and what data we have stored in Hive

    int countTodaySteps(StepCount value) {
        final List<DaySteps>? todayList =
            stepBox!.values.where((element) => element.date == todayDate).toList();
        final List<DaySteps>? yesterdayList = stepBox?.values
            .where(
                (element) => element.date == todayDate.subtract(Duration(days: 1)))
            .toList();
         final int todaySteps = (todayList?.length ?? 0) >= 1 &&
                (value.steps < (todayList?.first.steps ?? 0))
            ? (todayList?.single.steps ?? 0) + value.steps
            : value.steps -
                (yesterdayList!.isEmpty ? 0 : (yesterdayList.single.finalDayValue));
        _steps.setValue(todaySteps);
        final int finalDayValue =
            value.steps < todaySteps ? todaySteps : value.steps;

        stepBox!.put(
            todayDate.toString(),
            DaySteps(
                date: todayDate, steps: todaySteps, finalDayValue: finalDayValue));
        if (todaySteps > 2000) {
          getStepsTodayForRewardDependOnPlatform();
        }
        return todaySteps;
      }

**Comment by Dev-hwang** [comment]
@BJRichardsAZ

Is the ISAR database working in background Isolate? I've checked and it doesn't seem to be able to open the database in the background. How about using a plugin like `sqflite`?

**Comment by zawadZwd** [comment]
Hello @Dev-hwang 

> Is the ISAR database working in background Isolate? 

Well kinda. Isar supports isolations ( https://isar.dev/recipes/multi_isolate.html#when-to-use-multiple-isolates )

> How about using a plugin like sqflite?

Sqflite is snippy 😃 so lots of people - including me hehe - are looking for alternatives 😃 
I was trying to implement the objectbox - similar db to isar - to your plugin with receive port, but with no result 😞

**Comment by Dev-hwang** [comment]
@BJRichardsAZ @zawadZwd 

Check this example.

**Comment by zawadZwd** [comment]
Hey @Dev-hwang  
your example works perfectly fine, however I believe the pass data with db path won't be necessary - check this issue on Isar plugin: https://github.com/isar/isar/issues/313

**Comment by BJRichardsAZ** [comment]
After testing the example, it works great, I was even able to access the data and display it within the example ui, however, when trying to implement this into our app it seems that something is still not working. I think the issue lies in the fact that I'm trying to keep the code for foreground package outside the main.dart file. Currently all of the foreground task code is located in a different file foreground_task.dart. The start and initialize functions are then being called in our step count page file and I'm passing a receivePort from the UI layer for that page into the functions. When the user visits the stepcounter page, it should check permissions and then start the foreground task. I can see that the functions are getting properly called, and the log for the foreground task prints that the foreground service has started, but no notification appears on the phone and I cant verify if the process is actually running or not; I can't determine why this is the case.

**Comment by BJRichardsAZ** [comment]
I believe I have the resolved the issue, had a small error in my manifest file. Thank you for all your help!
