### ISSUE TITLE
Foreground Process Seems to be killed after a period of time

### ISSUE THREAD

**Issue by BJRichardsAZ** [Dev-hwang/flutter_foreground_task#76]
We have implemented a pedometer package using isar database and flutter foreground task to allow a step counter to persist even if the user kills the app or hasn't opened it for some time. It's working fine initially, but after a few hours (we've noticed the biggest issue being overnight) the foreground service notification stays present, but we no longer see the data update in the foreground service notification.  The app will no longer resume counting steps until the user reopens the app to start the process again, which causes some inconsistencies with the data when steps are counted.

**Comment by Kimsangwon0509** [comment]
was it ios???
in my case, we periodically communicate with our server evert 5 minutes.
It's working fine for 3 days and i keep on test.
My question is, Does your app work periodically or when the event occurs, your app works?

**Comment by Dev-hwang** [comment]
This issue seems to be related to [Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby) on the Android platform.

When using the service for extended periods of time, it is recommended to turn off battery optimization by calling the `FlutterForegroundTask.requestIgnoreBatteryOptimization()` function.

Please let me know if the issue persists.

**Comment by Dev-hwang** [comment]
@Kimsangwon0509 

iOS에서 지속적인 백그라운드 처리를 하는 것은 어렵다고 Readme에도 작성을 해놓았습니다. 포그라운드에서는 정상적으로 동작하나 백그라운드에서는 플랫폼의 제한 때문에 몇 초~분 후 결국 서비스가 절전 상태로 빠지게 됩니다. 예외도 있기는 하지만 보통 음악 재생, 파일 다운로드 등과 같이 한정되어있구요.

문제를 해결할 수 있는지 한 번 더 확인해보겠습니다. 좋은 방법이 있다면 알려주세요.

https://hamait.tistory.com/715

https://yagom.net/forums/topic/%EB%B0%B1%EA%B7%B8%EB%9D%BC%EC%9A%B4%EB%93%9C%EB%A1%9C-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%9D%84-%EA%B3%84%EC%86%8D%ED%95%B4%EC%84%9C-%EC%82%B4%EB%A0%A4-%EB%86%93%EB%8A%94/

**Comment by BJRichardsAZ** [comment]
We are currently ignoring battery optimizations and it is required before the foreground service will start. The interesting thing is that in the example app you sent over it doesn't require battery optimization to be ignored. It also doesn't stop functioning after leaving the app closed for elongated periods of time, which seems counter intuitive. I'm wondering if it might be related to where we are calling the WithForegroundTask widget, as the direct child of it in the example app is a scaffold, whereas in our app we are calling it and providing a class that returns a future builder as its child:
  
    home: WithForegroundTask(
              child: FutureBuild(
                  initialization: _initialization, inviteCode: inviteCode)),
     );
     
     This future builder is just waiting on firebase to initialize before loading the main UI of the application, but this is the only place where the setups seem to differ in a larger way. Let me know if you have any ideas.

**Comment by Dev-hwang** [comment]
It seems to be fine on real devices with Android 9.0 and lower. Can I know the development environment and the version of the device you tested?

I will continue to track down the issue.

**Comment by Dev-hwang** [comment]
Upgraded the coroutine version and changed the way it is used. Would you like to test it by adding a line like below?

```yaml
dependencies:
  # flutter_foreground_task: ^3.7.3
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

**Comment by Faiizii** [comment]
I also facing the same issue. I tried your suggestion of using lib directly git but still facing the issue. Also I am trying to upload the `Position` data to firebase. When I put ma app to background (not terminated) `TaskHandler` stops handling any networking request.
Check my code below 

````
StreamSubscription<Position>? _streamSubscription;

  @override
  Future<void> onStart(DateTime timestamp, SendPort? sendPort) async {
    print('onStart of foreground service called');
    final positionStream = Geolocator.getPositionStream();
    _streamSubscription = positionStream.listen((event) {
      print('position $event'); // this is being not called in background mode.
      saveToFirebase(event);
      sendPort?.send(event);
    });
  }
````

**Comment by Faiizii** [comment]
Also this might help 
https://stackoverflow.com/questions/67039618/getting-location-updates-in-foreground-service-isnt-working-when-app-is-moved-t

**Comment by Dev-hwang** [comment]
I tried running the foreground service for 2 days and there was no problem.

<img src="https://user-images.githubusercontent.com/47127353/168502384-a90bf5bb-ceb4-45cf-a87b-4f4c00f34007.jpg" height="120">
<img src="https://user-images.githubusercontent.com/47127353/168502379-7f8fad2f-3918-4284-ba04-6305940c6fef.jpg" height="150">

It seems that compatibility with other plugins or limitations of the Android platform should be considered. As shown in the link above, using the `foregroundServiceType` option in the `AndroidManifest.xml` file may also help.

```xml
<service
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="location" />
```

**Comment by Dev-hwang** [comment]
move issue #223
