### ISSUE TITLE
App getting killed in background

### ISSUE THREAD

**Issue by akshg05** [Dev-hwang/flutter_foreground_task#80]
I am using the Foreground task to keep my app alive when it's in the background.
However, after some time which could be for 15 mins or 30 mins or an hour as well being uncertain, the app is killed along the foreground service.
I do not do anything substantial in the foreground task other than what's in the example. I am using it to only keep the app alive in background.
I am using Android 11 real device and have not called for batteryOptmization.
Any guidance on this?

**Comment by SomeoneIsWorking** [comment]
I'm getting reports, after client goes to sleep and wakes up, task notification disappears.
Even when ignoring battery optimizations.

**Comment by h2210316651** [comment]
Some device manufacturers like Samsung, one plus,oppo, vivo and xiaomi have their own battery savers which kill the app and all of it's services no matter what. You have to explicitly disable them on your app settings and sadly there is no other way out.

**Comment by SomeoneIsWorking** [comment]
@h2210316651 I'm thinking of setting up a periodic firebase messaging that will try to restart the service it has stopped working. Do you think it will help?

**Comment by h2210316651** [comment]
> @h2210316651 I'm thinking of setting up a periodic firebase messaging that will try to restart the service it has stopped working. Do you think it will help?

Can you elaborate. firebase messaging as in Firebase Cloud Messaging?

**Comment by SomeoneIsWorking** [comment]
@h2210316651 Yes FCM. When the app receives an FCM push notification, its handler will check if the service is running and run it if it isn't.

**Comment by hardikamal** [comment]
@SomeoneIsWorking @h2210316651 @akshg05 @Dev-hwang - Any solution found for this?

**Comment by SomeoneIsWorking** [comment]
> Any solution found for this?

@hardikamal We moved to using Firebase Cloud Messaging as the trigger mechanism for the recurring task

**Comment by RohitSadioura** [comment]
Service is Getting Closed After Some Time Notification is disappearing . even after disabled battery optimization . any solution for this ?

**Comment by aBuder** [comment]
I have same problem. @RohitSadioura Did you find any solution?

**Comment by RohitSadioura** [comment]
No @aBuder

**Comment by Dev-hwang** [comment]
@aBuder 

It would be helpful if you could tell me what caused the service to kill. This may be a memory problem or the service may be terminated according to the policy of a specific manufacturer and device. Using a service like the `Firebase Crashlytics API` may be able to identify the problem.

**Comment by Dev-hwang** [comment]
@aBuder 

If you're not communicating with dart main isolate, the settings below may help. 

```xml
<service
        android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
        android:process=":remote" />
```

However, this separation of processes has the disadvantage of not being able to control the service.

**Comment by Dev-hwang** [comment]
@aBuder @RohitSadioura 

Also try the options below:
```xml
<application
        android:label="flutter_foreground_task_example"
        android:icon="@mipmap/ic_launcher"
        android:persistent="true"> <!-- this -->

</application>
```

<img width="816" alt="image" src="https://github.com/Dev-hwang/flutter_foreground_task/assets/47127353/89d6f41a-9290-431b-8dac-b5edcea90d9c">

**Comment by aBuder** [comment]
No App will still closed

**Comment by erisanolasheni** [comment]
The problem I am trying to tackle now is app stops working in the background after some time but retains the sticky foreground notification. Our app counts steps so we make it in a way that it does that in the background and shows how many steps are counted in the sticky foreground notification. But many reports say the counter stops working and hangs at "x counted steps". I think this happens when the operating system tries to free resources by restarting the foreground service.

**Comment by Dev-hwang** [comment]
move issue #223
