### ISSUE TITLE
Task stays open when app is closed from the running apps list

### ISSUE THREAD

**Issue by yoavrofe** [Dev-hwang/flutter_foreground_task#86]
Sometimes the user may try to close the app by swiping it off the running apps list. However, this doesn't close the foreground process. Is there a way to remove the task in this scenario?

**Comment by cheeco83** [comment]
@yoavrofe I have experienced the same problem. I tried solving it by using the AppLifecycleState - Observer and stop the service once the app lifecycle is disposed, as described here: https://www.youtube.com/watch?v=DqJ_KjFzL9I On app-closure, the stopService() - function is called as expected, but unfortunately the background task is still not stopped.

A solution would be highly appreciated!

**Comment by cheeco83** [comment]
@yiavrofe I think the solution is far more simple than expected! Browsing through the issue tracker, I found the following answer from the developers. [link](https://github.com/Dev-hwang/flutter_foreground_task/issues/34)

Worked perfectly for me!

**Comment by yoavrofe** [comment]
Thanks a lot, @cheeco83 ! It works perfectly for me as well.
