### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_foreground_task/flutter_foreground_task.dart'. 

### ISSUE THREAD

**Issue by meridorkobi** [Dev-hwang/flutter_foreground_task#88]
Hello
I'm trying to use the plugin 

**In pubspec.yaml**
`flutter_foreground_task:`

**in Dart file**
`import 'package:flutter_foreground_task/flutter_foreground_task.dart';`

What can I do?

**Comment by behradkhadem** [comment]
Usually closing and reopening the IDE alleviates this problem. If you use VS Code check output tab after running `flutter pub get` to see possible errors. An other thing that you can try is  running `flutter clean` to remove everything in your build folder and running `flutter pub get` again.
