### ISSUE TITLE
Can't close my foreground task when I exit the app

### ISSUE THREAD

**Issue by DamienMrtl** [Dev-hwang/flutter_foreground_task#91]
I'm using the foreground task to prevent the app to sleep and still receive firebase events when the user changes app or screen is off.

The problem is I want to close my foreground task when the app is killed. I can't find a way from within the task to detect the app is killed and then close the task.

From the app a tried to listen to `AppLifecycleState.detached` using the `didChangeAppLifecycleState()`, I can detect the event but then when I call FlutterForegroundTask.stopService(); it doesn't close the foreground service. And I get this error: 
`W/FlutterJNI( 5009): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 39`

**Comment by DamienMrtl** [comment]
Ok so I found out there is a Flag on android to achieve this:
`<service android:name="com.pravera.flutter_foreground_task.service.ForegroundService" android:stopWithTask="true" />`

**Comment by DanielHoltebo** [comment]
Spent A LOT of time trying to get the app to close the foreground task when the app was closed. I think this flag should be more visible in the documentation on the flutter package page @Dev-hwang !
Other than that, great package! :)

**Comment by h2210316651** [comment]
@DanielHoltebo the very point of a foreground task is to execute stuff even when the app is closed. I think you should have known it. No offense.

**Comment by DamienMrtl** [comment]
@h2210316651
Most of the time the need for this kind task is to keep the app active when the user switches to another app or the screen sleeps.

**Comment by gri38** [comment]
> @h2210316651 Most of the time the need for this kind task is to keep the app active when the user switches to another app or the screen sleeps.

Hi. I agree, and that's my case. But when the user "closes all" apps (you know: swipe or click squere => it displays all apps on android, then you can close all), you may expect the foreground task exits.
Especially given this "problem": https://github.com/Dev-hwang/flutter_foreground_task/issues/120
