### ISSUE TITLE
Is it possible/recommended to include API calls or webhook connections in a service?

### ISSUE THREAD

**Issue by NamanShergill** [Dev-hwang/flutter_foreground_task#93]
In case the app was killed and the service needs to update the data to a server?

Not exactly an issue, just looking for a bit of a recommended practice advice.

**Comment by h2210316651** [comment]
From an android perspective:
A foreground task ( service ) is something that the user is aware of as opposed to a background service. Think of it like a music player. It is pretty unusual that it gets killed by the OS until and unless the user does so. You shouldn't worry about the service being killed. As for your question the foreground service pretty much stays alive even when the app is killed.

**Comment by h2210316651** [comment]
@Dev-hwang I recommend this issue closed.

**Comment by NamanShergill** [comment]
Thanks! Wasn't sure if it was fine to have webhooks in it. I'll close the issue now.
