### ISSUE TITLE
launchApp method call only works onNotificationPressed but not in onStart or onEvent.

### ISSUE THREAD

**Issue by h2210316651** [Dev-hwang/flutter_foreground_task#96]

**Comment by Dev-hwang** [comment]
Did you request and grant "android.permission.SYSTEM_ALERT_WINDOW" permission? The above permission is required to use the launchApp function in apps on Android 10 (API level 29) and higher.

**Comment by Dev-hwang** [comment]
https://developer.android.com/guide/components/activities/background-starts

To avoid the restriction, this plugin uses the "android.permission.SYSTEM_ALERT_WINDOW" permission.
