### ISSUE TITLE
how to listen to changes instead of interval

### ISSUE THREAD

**Issue by AliEasy** [Dev-hwang/flutter_foreground_task#99]
Hi
I am building an app with purpose of getting call history even in background and I want to trigger the service only when phone is making a call (with the help of [https://pub.dev/packages/phone_state](https://pub.dev/packages/phone_state) )
So in my case `onEvent` getting called by an interval is useless

How can I manage to do that?

**Comment by Dev-hwang** [comment]
If you want to call `onEvent` only once, set `isOnceEvent` in ForegroundTaskOptions to `true`.

**Comment by samnbd** [comment]
@AliEasy please check this solution [https://github.com/Dev-hwang/flutter_foreground_task/issues/126](https://github.com/Dev-hwang/flutter_foreground_task/issues/126)
